### ISSUE TITLE
Testing version 1.0 

### ISSUE THREAD

**Issue by orthes** [orthes/medium-editor-insert-plugin#111]
This issue is addressed mainly to the plugin's contributors.

First of all, thank you for all your help with testing, fixing and enhancing this plugin. It started as a quick prototype of image handling in medium-editor, and after a year evolved to much bigger scale, than I ever imagined. 

- 22 contributors
- 25 releases
- 43 pull requests
- 67 issues (62 closed)
- 89 forks
- 241 commits
- 318 stars
- hundreds of downloads (there really isn't a way to see this statistic somewhere somehow?)
- 2000+ monthly visits

Thank you for all your work on version ```0.*```. 

As the plugin was growing, it started to be obvious, that initial simple structure isn't sustainable. The problem was not only maintaining the plugin, but limitations of the structure resulted in much bigger issues (https://github.com/orthes/medium-editor-insert-plugin/issues/83).

So here we are, on the edge of version ```1.0```. For the last month I completely rewrote the plugin. Initially, I thought, it will be simple one-to-one refactoring, but I quickly realized, that if I'm refactoring, it's better to make it right this time and make version ```1.0``` much closer to the current [medium.com](http://medium.com) version.

**What I managed to do in the last month could found in [1.0 branch](https://github.com/orthes/medium-editor-insert-plugin/tree/1.0).**

So here comes the reason for this post. I need your help testing. ```1.0-alpha.2``` was released today with complete images and embeds addons. There might be functions missing and maybe you'll immediately think of ideas to make it better. But for now, I would need you to test, what is done, and focus on bug fixes and performance issues, so we can release this version as soon as possible, and then there will be time to improve it.

So what needs to be done is:
- Bug fixes
- Browser compatibility
- Documentation (https://github.com/orthes/medium-editor-insert-plugin/issues/108)

One last thing: **backwards compatibility**. As we adopted [semantic versioning](http://semver.org), the major release is allowed to break backwards compatibility. But I want to make it as painless as possible. As you can see in an example (https://github.com/orthes/medium-editor-insert-plugin/blob/1.0/examples/index.html#L110), configuration changed a bit and configuration is the only place, where backwards compatibility should breaks.

Class names were changed, but CSS uses both old and new ones, so content created with version ```0.*``` can be maintained with the new version. After the first use, version ```1.0``` replaces old classes with the new ones (https://github.com/orthes/medium-editor-insert-plugin/blob/1.0/src/js/images.js#L92).

So one more thing, that needs to be checked, is backwards compatibility - if old content could be edited with the new version.

Thank you in advance. With your help, stable version could be released in a week or two. Depending on a number of issues we run into.

/cc @ai, @nleush, @vexus2, @KELiON, @OmniaGM, @fbessadok, @olleicua, @miloshadzic, @brenfrow, @Siron, @enzoz, @jonathonsim, @merqurio, @flamerohr, @j0k3r, @indrasantosa, @maxkirchoff, @inssein, @iparamonau

**Comment by orthes** [comment]
OK. It looks like all major problems were solved, so I moved 1.0 into beta stage. The 1.0 should be pretty much usable (at least I started using it on new projects). Please, try it out and if we don't run into big problems, we can release it as the first stable release.

The last thing is to write a documentation as mentioned in #108. I will look into that as soon as I will have some time.

**Comment by zakbach** [comment]
I just tried out the 1.0 beta, it says Handlebars is not defined? Since it's a beta already, could you perhaps write up a quick tl;dr on how to use it?

**Comment by orthes** [comment]
@zakbach Of course. My bad. I've updated the [1.0 README](https://github.com/orthes/medium-editor-insert-plugin/blob/1.0/README.md). The 1.0 version has a few more dependencies than the previous one.

**Comment by orthes** [comment]
I've finally created the [documentation in Wiki](https://github.com/orthes/medium-editor-insert-plugin/wiki) so both 0.3 and 1.0 documentations are in a one place.

**Comment by zakbach** [comment]
Great. Thanks!

**Comment by orthes** [comment]
It looks like all major issues were resolved and a documentaion is ready, so it is a time to finally release 1.0 version. Thank you for your testing and contributions.

**Comment by j0k3r** [comment]
Awesome :clap:
