### ISSUE TITLE
[1.0] Use url as image src instead of data uri

### ISSUE THREAD

**Issue by zh-daniel-huang** [orthes/medium-editor-insert-plugin#128]
If we upload several large images, it will make entire content size too huge to transport quickly since we use base64 embed image.

Could we use URL to be image src which is returned from server after successful uploading?

**Comment by zh-daniel-huang** [comment]
Yes, it already work like that. I forgot to check the latest version.

**Comment by djyadav** [comment]
Even after successful upload on server, Image source is still the same base64 code.

I'm using ExpressJS with jquery-file-upload-middleware.

Any Idea, how to put that on work ?

**Comment by orthes** [comment]
Make sure your server returns absolute path to an uploaded image. A preview image (base64) is replaced by a path to an uploaded image only if a browser successfully loads the uploaded image first. If the image couldn't be loaded, the preview image is never replaced.

I had the same problem. Then I found out that a server returned relative path (uploads/image.jpg), but the editor was in subfolder /admin which resulted in unexisting image /admin/uploads/image.jpg

**Comment by djyadav** [comment]
Yeah, I m getting absolute path for the image from the server.
Please check my response if there are any issues with that -
![response](https://cloud.githubusercontent.com/assets/8155498/6501375/61ea6f94-c33d-11e4-9e0c-f0ae10f98a7c.png)

However, If I try to access that absolute path to image in broswer, I get a Json not an image.
Trying to figure that out but not getting any solution.

![json2](https://cloud.githubusercontent.com/assets/8155498/6501404/de761158-c33d-11e4-88d3-cec60e7ef89c.png)

**Comment by orthes** [comment]
And there is your problem. An uploaded image has to be accessible in order to replace a base64 preview.

**Comment by djyadav** [comment]
hehehhe I got that . Its working great now.

Thanks a lot buddy.
