### ISSUE TITLE
Embed not working on firefox

### ISSUE THREAD

**Issue by scashin133** [orthes/medium-editor-insert-plugin#132]
When I try to write the url for the embed in firefox the keyup event is firing but the placeholder is not going away. If I wrap the br tag with a p then it seems to work.

**Comment by scashin133** [comment]
I forgot to mention that this is on the 1.0.0 branch.

**Comment by orthes** [comment]
Thanks for the report. I will look at it today.

**Comment by orthes** [comment]
You were right. The problem was with ```br``` tag not being wrapped in ```p```. In Chrome it is done automatically, but Firefox doesn't do that. I've made sure that it is wrapped correctly in all browsers. Now it should work correctly.

**Comment by scashin133** [comment]
Awesome! Thanks for fixing this so quickly. Also congratulations on the 1.0 launch. I've found this version to be way easier to work with than the previous one.
