### ISSUE TITLE
Question about embed layouts and custom styles.

### ISSUE THREAD

**Issue by Jiert** [orthes/medium-editor-insert-plugin#133]
Thanks so much for your hard work on this plugin. I'm excited to ditch our old Rich Text Editor and start using the Medium clone along with your insert plugin.

I wanted to ask if you had plans to support embed layout options, similar to how the medium.com editor works:

![screenshot 2015-01-27 17 19 04](https://cloud.githubusercontent.com/assets/590608/5930759/e2531e22-a648-11e4-97d5-a05730345a5d.png)

Also, I'm using this in an app that utilizes bootstrap. We serialize the output of the editor and then use that content in other rendered websites that must rely on bootstrap styles for layout. So where this plugin uses: 'medium-insert-images-left' I need to be able to apply 'pull-left', for example.

To do this, i'm overwriting Images.prototype.toolbarAction. Is there perhaps a better way to go about this that I'm not seeing?

I'm happy to contribute where possible.

Again, thanks for the plugin!

**Comment by orthes** [comment]
Currently there is no plan to add embed layout options. If you need it, feel free to implement it and submit a PR :)

About your second question. There is an easier way to do it. You can add callback functions to a left style configuration:

```javascript
$('.editable').mediumInsert({
    // ...
    addons: {
        images: {
            styles: {
                left: {
                    added: function ($el) {
                        $el.addClass('pull-left');
                    },
                    removed: function ($el) {
                        $el.removeClass('pull-left');
                    }
                }
            }
        }
    }
});
```

Something like this should work. All configuration options could be found here: https://github.com/orthes/medium-editor-insert-plugin/wiki/v1.0-Configuration

**Comment by Jiert** [comment]
Ah, wonderful, thanks!
