### ISSUE TITLE
Cannot support IE8

### ISSUE THREAD

**Issue by cnyb-kwange** [orthes/medium-editor-insert-plugin#135]
First of all, thanks for your 'medium-editor-insert-plugin'.
I love this plugin and plan to use it in my project,
but found it is not supporting IE8,
I'm chinese, in my country many people using IE8 browser,
so...  is there any method can resolve this problem?
Thanks!

**Comment by orthes** [comment]
I'm sorry, but since usage of IE8 and IE9 is finally declining worldwide and even big companies like Google have stopped supporting them, I have no plans regarding IE8.

But if you manage to get it working on IE8, feel free to contribute to the plugin and submit a pull request.
