### ISSUE TITLE
All Placeholders Disappear

### ISSUE THREAD

**Issue by herwinlesmana** [orthes/medium-editor-insert-plugin#143]
Hello,

In one page I have 3 divs using medium editor:
1 div (title) - medium editor only
2 divs (thumbnail and post) - medium editor with insert plugin

![image](https://cloud.githubusercontent.com/assets/1695191/6184826/4827369a-b399-11e4-948f-9cce2be2ced7.png)

Once I clicked in that page, the placeholder text at thumbnail and post div disappear and not coming back again. This is not happened with the title div.

![image](https://cloud.githubusercontent.com/assets/1695191/6184836/5be59884-b399-11e4-83b0-f970ccb2fe03.png)

**Comment by j0k3r** [comment]
Could you provide the html content or *even better* a jsfiddle that reproduce your problem?

**Comment by herwinlesmana** [comment]
I reproduce it here: https://jsfiddle.net/herwinlesmana/sczvwmry/8/

**Comment by orthes** [comment]
Thanks for the report. I will look at it.

**Comment by orthes** [comment]
I fixed it. You can try the latest changes in the master branch (either by downloading [ZIP](https://github.com/orthes/medium-editor-insert-plugin/archive/master.zip), cloning it using git, or using #master branch in bower)

**Comment by herwinlesmana** [comment]
Works like a charm. Thank you!
