### ISSUE TITLE
Remove Jquery dependency 

### ISSUE THREAD

**Issue by julianfox** [orthes/medium-editor-insert-plugin#144]
Hello,
I use Angular and i don't want to add Jquery lib in my program, is it easy to remove the Jquery dependency if i use my own lib for update the pictures ?

**Comment by orthes** [comment]
Unfortunately no. jQuery is necessary dependency. The plugin uses it heavily for all DOM manipulations and even 2 other plugin's dependencies (blueimp-file-upload and jquery-sortable) use jQuery themselves. If you don't want to use jQuery, you can try some other alternatives like [Zepto](http://zeptojs.com/), but I can't guarantee you it will work.
