### ISSUE TITLE
Backspace in empty div

### ISSUE THREAD

**Issue by herwinlesmana** [orthes/medium-editor-insert-plugin#145]
Hello,

Try to hit backspace in empty div. The caret will move up one line to the padding area, then type something, it will give you uncontrolled return.

You can try with thumbnail and post divs here: https://jsfiddle.net/herwinlesmana/sczvwmry/11/
![image](https://cloud.githubusercontent.com/assets/1695191/6190998/c430b7cc-b3d8-11e4-8a7c-f1231e97a8f5.png)

**Comment by orthes** [comment]
I fixed it. It should work now even in your jsfiddle.
