### ISSUE TITLE
Medium insert button position when using embed

### ISSUE THREAD

**Issue by herwinlesmana** [orthes/medium-editor-insert-plugin#146]
Hello,

When I used the embed function, medium insert button goes to top left instead of disappearing.

You can try with this jsfiddle: https://jsfiddle.net/herwinlesmana/sczvwmry/11/ at thumbnail or post divs
![image](https://cloud.githubusercontent.com/assets/1695191/6191330/21d5ea9e-b3db-11e4-9c2c-7d9c21b273bb.png)

**Comment by kunalchaudhari** [comment]
I encountered the same. In my case the editor element has style applied ```position: relative```. When i removed that style it fixed the issue.

**Comment by orthes** [comment]
@kunalchaudhari Your solution worked, but it was kind of a hack, because the real problem was that the buttons should not be visible at the first place. I fixed it now.

**Comment by kunalchaudhari** [comment]
@orthes Thanks for fix. +1:
