### ISSUE TITLE
New Image Not Uploaded

### ISSUE THREAD

**Issue by herwinlesmana** [orthes/medium-editor-insert-plugin#153]
Hello,

When I insert new image to populated div, the image not uploaded to server. The image appears as data/image.

![image](https://cloud.githubusercontent.com/assets/1695191/6458884/620f9932-c1bb-11e4-9a84-23d1468e3cb2.png)

The first <img> is the new inserted image.

**Comment by orthes** [comment]
Does your server return correct response?  Look into network requests and make sure everything works fine there. It should look something like this:

![screen shot 2015-03-03 at 09 56 08](https://cloud.githubusercontent.com/assets/312938/6459130/d160e0fa-c18b-11e4-98f0-a9145500145f.png)

**Comment by orthes** [comment]
Duplicate #128
