### ISSUE TITLE
Having issues with code below throwing Uncaught TypeError: undefined is not a function

### ISSUE THREAD

**Issue by hraynaud** [orthes/medium-editor-insert-plugin#154]
I've just done a bower install of all of the latest dependencies but  getting these errors. It's related to this block. Any assistance would be appreciated. thanks.

    Core.prototype.editorActivatePlaceholder = function (el) {
        var $clone = $(el).clone(),
            cloneHtml;

        $clone.find('.medium-insert-buttons').remove();
        cloneHtml = $clone.html().replace(/^\s+|\s+$/g, '').replace(/^<p( class="medium-insert-active")?><br><\/p>$/, '');

        if (!(el.querySelector('img')) &&
            !(el.querySelector('blockquote')) &&
            cloneHtml === '') {

            el.classList.add('medium-editor-placeholder');
            this._hideInsertButtons($(el));
        }
    };

**Comment by orthes** [comment]
I released a bug fix now. Try updating to the latest version and see if it helps.

**Comment by hraynaud** [comment]
Awesome thanks will do.
