### ISSUE TITLE
Integrating with ExpressJs

### ISSUE THREAD

**Issue by djyadav** [orthes/medium-editor-insert-plugin#155]
After loading all the dependencies, It works fines and images are uploaded to the same folder i was using for my other upload purposes.

But, I'm not sure about its functionality and Cant configure  the upload complete event and where is the path to the upload folder specified.

**Comment by orthes** [comment]
Path to the upload folder is specified on the server side and not in the plugin itself. We use blueimp's jQuery File Upload for uploading so look over here to their documentation: https://github.com/blueimp/jQuery-File-Upload/wiki#javascript
