### ISSUE TITLE
how to get uploading image width and height

### ISSUE THREAD

**Issue by cnyb-kwange** [orthes/medium-editor-insert-plugin#156]
I have a guestion..

how to get uploading image width and height in the showImage function?

--------------------------------------------------------------------------------------------------------
            domImage.onload = function () {
                data.context.find('img').attr('src', domImage.src);
                // why I can't get image real width and height here?
                // when uploading multiple pictures, the first one can be got width and height, but the other cannot.
            };
--------------------------------------------------------------------------------------------------------

thanks

**Comment by orthes** [comment]
When I try this, it works. For multiple images too.

```javascript
domImage.onload = function () {
    data.context.find('img').attr('src', domImage.src);
    console.log(domImage.width);
    console.log(domImage.height);
};
```

**Comment by cnyb-kwange** [comment]
thank you very much !!!!!!!!!!!!!! :)
