### ISSUE TITLE
What structure of response should be after uploading file?

### ISSUE THREAD

**Issue by harrykiselev** [orthes/medium-editor-insert-plugin#157]
Hello! Thanks for the plugin.

Today I faced a problem with JSON response from a server after uploading a file.

Can I try add into documentation a pair of words about JSON response that server returning after upload a files? At least reference to [jquery-upload documentation](https://github.com/blueimp/jQuery-File-Upload/wiki/JSON-Response). :)

**Comment by orthes** [comment]
Yes, good point. You can update our wiki with a sample code and link to jquery-upload documentation. Thanks.

**Comment by harrykiselev** [comment]
Pavel @orthes, it's [done](https://github.com/orthes/medium-editor-insert-plugin/wiki/JSON-Response). It's ok? :)

**Comment by orthes** [comment]
:+1:
