### ISSUE TITLE
<figure> and <figcaption> tags are not accepted by DOMDocument->loadHTML

### ISSUE THREAD

**Issue by Dmatafonov** [orthes/medium-editor-insert-plugin#159]
I'm cleaning user submitted html with php  DOMDocument, so I can get rid all iframes execpt youtube etc..
But figure> and figcaption> are not allowed in this library, so I have to clean them out before actually sending to server. 
Is it neccessary to user figure and figcapture? Consider using regular div...

**Comment by orthes** [comment]
The plugin relies on HTML5 and CSS3. If I were on your place, I would think about using a library that supports HTML5 instead of DOMDocument.
