### ISSUE TITLE
Youtube embeds on https sites is not working

### ISSUE THREAD

**Issue by Dmatafonov** [orthes/medium-editor-insert-plugin#160]
iframy in lib is set http strictly:

```javascript
/** Default values */
    var pluginName = 'mediumInsert',
        addonName = 'Embeds', // first char is uppercase
        defaults = {
            label: '<span class="fa fa-youtube-play"></span>',
            placeholder: 'Paste a YouTube, Vimeo, Facebook, Twitter or Instagram link and press Enter',
            oembedProxy: 'http://medium.iframe.ly/api/oembed?iframe=1',
```

so when I try to embed youtube iframe on secure site

Mixed Content: The page at 'https://beta.tradernet.ru/feed/' was loaded over HTTPS, but requested an insecure XML

**Comment by Dmatafonov** [comment]
sorry, my fault - I've put http link in options

**Comment by SqrFactor** [comment]
jquery.min.js:4 Mixed Content: The page at 'https://sqrfactor.com/post/article' was loaded over HTTPS, but requested an insecure XMLHttpRequest endpoint 'http://medium.iframe.ly/api/oembed?iframe=1&url=http%3A%2F%2Fmedium.iframe.ly%2Fapi%2Foembed%3Fiframe%3D1&_=1526474496106'. This request has been blocked; the content must be served over HTTPS.

I'm getting the same error when I'm inserting video. How can I resolve it?

**Comment by orthes** [comment]
Yes. You can't use http://medium.iframe.ly as your oembedProxy in production. You have to sign up in your oEmbed service of choice and use your own link.
