### ISSUE TITLE
Hook into events

### ISSUE THREAD

**Issue by stevenleeg** [orthes/medium-editor-insert-plugin#161]
Hey there,

I'm currently running into a few use cases where it'd be super helpful to have one or both of the following features:

* Some way to run a callback after a successful image upload. `$('.editor').on('imageUploadSuccess', callback);` or something along those lines would be useful.
* A way to modify the `data` argument passed into `$.ajax` uploading/deleting an image using server-side scripts. This makes it difficult to use this plugin on Rails projects using CSRF tokens, as there's no way to pass them along with the request without actually modifying the plugin.

Is there any workaround to accomplish either of these things with the current version? If not, is this something that others would find useful enough to include in future versions?

Thanks in advance, and great work on this plugin!

**Comment by orthes** [comment]
Right now it's not possible, but you're right, it would be useful. You can submit a PR, if you've already added it into your project.
