### ISSUE TITLE
Medium editor 4.0 support

### ISSUE THREAD

**Issue by buger** [orthes/medium-editor-insert-plugin#164]
It recently bumped version with some major api changes. From things i noticed `activatePlaceholder` no more available, and placeholder does not work. But for sure there is more issue.

**Comment by daviferreira** [comment]
@orthes Hey man, sorry about yet another major bump, but this was like a reset for us so we start doing things right when it comes to versioning and also we removed a lot of exposed methods and came up with a cleaner API. I promise things will be smoother from now on :grin: 

Let me know if you need any help getting things working, I can jump in. And once again thanks for the awesome plugin :+1:

**Comment by orthes** [comment]
Yes, I've seen, but I didn't have time to test it yet.

@daviferreira Thanks! I'm looking forward to cleaner versioning, so I can set up looser dependencies and rely on you guys that upgrading from 4.0 to 4.1 should be smooth.

If I run into problems, I will definitely contact you. Thanks for the great editor :)

**Comment by orthes** [comment]
Version 1.5.0 now supports medium-editor 4.0
