### ISSUE TITLE
Using new version of plugin with rails

### ISSUE THREAD

**Issue by tezzataz** [orthes/medium-editor-insert-plugin#165]
Hi Guys,

Upgraded to the new version but struggling to make it work with rails and handling the JSON responses.

I used the following to make v0.3 work with rails and it works perfectly:
https://github.com/orthes/medium-editor-insert-plugin/issues/27

The new version doesn't seem to like how the controller renders the JSON.

Just wanted to know if anyone has had any success making the new version work in rails and how you handle the responses in the controller?

Cheers.

**Comment by orthes** [comment]
Make sure your server returns JSON response in a format described here: https://github.com/orthes/medium-editor-insert-plugin/wiki/Server-response

**Comment by tezzataz** [comment]
@orthes yep I already have it output the response in that format. The problem seems to be that paperclip isn't recognising the file anymore, and not uploading the file to the server in the first place so it's obviously not giving a response of any kind. 

I just need to find away for paperclip/ my controller to recognise the file that's been attached.

**Comment by orthes** [comment]
Since version 1.0 we're using blueimp's jQuery-File-Upload for image uploading. In their documentation they have a Rails example: https://github.com/blueimp/jQuery-File-Upload/wiki/Rails-setup-for-V6 . I hope it helps, because I'm not a Ruby guy.

**Comment by tezzataz** [comment]
After a day of tweaking, finally got it working, that guide makes makes it even more confusing.

The problem is that the base64 response parameters that were being passed to the rails controller weren't being processed, if that makes any sense.  I'll try and write up a few things to help others.
