### ISSUE TITLE
Documentation for creating new addons

### ISSUE THREAD

**Issue by boosis** [orthes/medium-editor-insert-plugin#166]
Hi,

I was wondering if there is any documentation about creating new addons?

Thanks

**Comment by j0k3r** [comment]
I don't think so. But you can learn a lot using current addons (embed & images).

**Comment by orthes** [comment]
Thanks for pointing that out. This definitely should be in our documentation. As @j0k3r said, for now you can learn from the current addons.

The only mandatory method an addon has to have is ```add()```: https://github.com/orthes/medium-editor-insert-plugin/blob/master/src/js/images.js#L148 . It is called when a user clicks on an addon button.

Also it has to have ```label``` option: https://github.com/orthes/medium-editor-insert-plugin/blob/master/src/js/images.js#L9

**Comment by boosis** [comment]
Thanks for the quick replies. I managed to create an add on to use Filepicker.io just copying and pasting code from Images add on :)

Thanks again.

**Comment by orthes** [comment]
:+1: When you'll feel it's ready and you'll have some tests written, feel free to submit a PR :)

**Comment by boosis** [comment]
I am not a js developer at all. As I said I just copied and pasted some code from the image add on. I wouldn't know where to start to make it PR ready. It's tightly coupled with the project I am working on.

I am more then happy to send you the file and you can do whatever needed :)

**Comment by orthes** [comment]
I added info about custom addons to our documentation: https://github.com/orthes/medium-editor-insert-plugin/wiki/v1.0-Custom-addons
