### ISSUE TITLE
About failed image uploads

### ISSUE THREAD

**Issue by tasarsu** [orthes/medium-editor-insert-plugin#168]
Hi, first of all thank you very much for this great plugin. 

As you know we see the image before uploading. I want to ask how do we remove base64 image if the upload fails. Because even the upload process fails image remains inline.

Best regards.

**Comment by orthes** [comment]
You're right. On some projects you want to remove a preview image if an image wasn't uploaded successfully, but on some projects you might want to leave it there and save it as it is, so you're sure it works even when a server has some problems - see https://github.com/orthes/medium-editor-insert-plugin/issues/167#issuecomment-88560853

I will add an option, so you can set your desired behavior.

**Comment by orthes** [comment]
In the latest version ```v1.6.0``` I've exposed ```fileUploadOptions``` option so you can configure upload script as you want.

[blueimp's jQuery-File-Upload](https://github.com/blueimp/jQuery-File-Upload/wiki/Options) has ```fail``` callback, so you can use that to handle failed uploads.

It might look like this:

```javascript
$('.editable').mediumInsert({
    // ...
    addons: {
        images: {
            fileUploadOptions: {
                fail: function (e, data) {
                    // data.errorThrown
                    // data.textStatus;
                    // data.jqXHR;
                }
            }
        }
    }
}
```

For more info see [blueimp's jQuery-File-Upload docs](https://github.com/blueimp/jQuery-File-Upload/wiki/Options#fail).
