### ISSUE TITLE
Plugin does not immediately initialise in IE11/Firefox

### ISSUE THREAD

**Issue by TruffleMuffin** [orthes/medium-editor-insert-plugin#172]
You need to press return to initialise the plugin UI, in Chrome however the plugin initialises immediately after clicking into the medium editor enabled field.

**Comment by j0k3r** [comment]
Which version of Firefox are you using ?

**Comment by TruffleMuffin** [comment]
Version is 37.0.1 (latest at time of writing)

**Comment by j0k3r** [comment]
Do you that problem on these pages too ?

 - http://orthes.github.io/medium-editor-insert-plugin/
 - http://daviferreira.github.io/medium-editor/

I've tested both on Firefox 37.0.1 and every thing goes well.

**Comment by TruffleMuffin** [comment]
Yes, on your demo page. 

If you clear all the text you have in the demo page. Then click away so that the placeholder is shown again. Click once and the plugin does not show the + at the side, click again or press return and it shows.

**Comment by j0k3r** [comment]
Thanks for steps to reproduce, it helps! I got the problem too on the demo page.

As a side note, I've integrated this plugin in our CMS and didn't get that problem.

**Comment by TruffleMuffin** [comment]
No worries. Hope its not too much of a headache to fix at some point. Really nice tool you have here.
