### ISSUE TITLE
Add option to remove caption from inserted content

### ISSUE THREAD

**Issue by arielsvn** [orthes/medium-editor-insert-plugin#173]
The plugin is great by the way. I'm planning to use it in a large project.

Is there any option to remove captions for inserted content?? that's not a requirement in my scenario.

Thanks.

**Comment by orthes** [comment]
Right now there is no such option. But you're right, it should be there.

**Comment by orthes** [comment]
In the latest version ```v1.6.0``` I've added ```captions``` options to both images and embeds addons. By default it is set to true, but you can change to to disable captions: https://github.com/orthes/medium-editor-insert-plugin/blob/master/src/js/images.js#L13

**Comment by arielsvn** [comment]
OK thanks :+1:
