### ISSUE TITLE
How to reject unsupported image types?

### ISSUE THREAD

**Issue by firedev** [orthes/medium-editor-insert-plugin#175]
I saw there is a callback to remove failed uploads. Is there a way to not initialize upload at all if the image is not an image? i.e. based file on extension?

**Comment by orthes** [comment]
In the latest version ```v1.6.0``` I've exposed ```fileUploadOptions``` option so you can configure upload script as you want.

One of the options is ```acceptFileTypes```: https://github.com/orthes/medium-editor-insert-plugin/blob/master/src/js/images.js#L19

For more options see [blueimp's jQuery-File-Upload docs](https://github.com/blueimp/jQuery-File-Upload/wiki/Options)
