### ISSUE TITLE
Turning off Grid Option

### ISSUE THREAD

**Issue by NoelBaron** [orthes/medium-editor-insert-plugin#180]
Hi there,

I'd like to hide the Grid button and disable all grid functionality, providing only the Wide, Left, and Right action buttons to the user. Have you provided an option for this? 

I tried excluding "Grid" from the styles option, but it did not suppress the button.

**Comment by orthes** [comment]
Try setting grid to false in styles.

**Comment by NoelBaron** [comment]
That did the trick, thanks!  Might I recommend a wiki update with a sample showcasing that capability?
