### ISSUE TITLE
about 'maxNumberOfFiles'

### ISSUE THREAD

**Issue by cnyb-kwange** [orthes/medium-editor-insert-plugin#181]
this option - maxNumberOfFiles , seems like can't work normally.

I added this option at the index page like this : 
$(function () {
    $('.editable').mediumInsert({
        editor: editor, // Instance of MediumEditor
        addons: {
            images: {
                uploadScript: 'upload.php',
                maxNumberOfFiles: 1
            } // images end
        } // addons end
    }); // mediumInsert end
});

is there any one knows how to use this option?

thanks

**Comment by j0k3r** [comment]
This option should be passed to `fileUploadOptions` as it's a parameter for jQuery File Upload ([see here](https://github.com/blueimp/jQuery-File-Upload/wiki/Options#maxnumberoffiles)).

BTW, the `uploadScript` is now deprecated. Here is your code fixed:

```
$(function () {
    $('.editable').mediumInsert({
        editor: editor, // Instance of MediumEditor
        addons: {
            images: {
                fileUploadOptions: {
                    maxNumberOfFiles: 1,
                    url: 'upload.php'
                }
            }
        }
    });
});
```
