### ISSUE TITLE
Problem updating content when the editor is created from a textarea

### ISSUE THREAD

**Issue by arielsvn** [orthes/medium-editor-insert-plugin#184]
From the MediumEditor readme:

> MediumEditor also supports textarea. If you provide a textarea element, the script will create a new div with contentEditable=true, hide the textarea and link the textarea value to the div HTML content.

MediumEditor subscribes to changes in the content editable `input` event using native methods to keep the `<textarea>` value synced with the editable region.

The problem is that this plugin uses jquery to trigger the `input` even on the editable region, and jquery only triggers handlers that have been subscribed through it. So changes from the embed plugins aren't updated on the textarea.

**Comment by orthes** [comment]
Duplicate #179
