### ISSUE TITLE
Recognizing  and inserting embed links when a user inputs a URL in the body

### ISSUE THREAD

**Issue by bhanusharma** [orthes/medium-editor-insert-plugin#188]
Today, the user has to enter the URL to embed a video or other embeds, by first clicking the +, then the video icon, then inputting inside the text field and hitting enter. 4 steps.

Is there any way for the user just enter a URL in the story editor, and recognize that as an embed input?

**Comment by orthes** [comment]
Right now it doesn't work like that, but it's definitely a good idea.

**Comment by orthes** [comment]
Added in #283
