### ISSUE TITLE
How to make work acceptFileTypes fileupload option

### ISSUE THREAD

**Issue by santiago-ervina** [orthes/medium-editor-insert-plugin#189]
Hi,
I saw in a closed issue that "acceptFileTypes" option for fileUploadplugin should work but I can't make it work, I'm using 1.6.0 but none file is rejected, is there any dependency or configuration needed to make it work?
thank you for this great plugin.

**Comment by orthes** [comment]
```acceptFileTypes``` should be used like this:

```javascript
$('.editable').mediumInsert({
    // ...
    addons: {
        images: {
            // ...
            fileUploadOptions: {
                acceptFileTypes: /(.|\/)(gif|jpe?g|png)$/i
            }
        }
    }
});
```

For more information see jquery-file-upload docs: https://github.com/blueimp/jQuery-File-Upload/wiki/Options#acceptfiletypes

**Comment by santiago-ervina** [comment]
Hi,
That's exactly what i'm doing but it doesn't work, I've checked in your demo http://orthes.github.io/medium-editor-insert-plugin/ and it has the same behavior, p.e. a php file is added and nothing shows on the screen but in the markup you'll find a "figure" tag with an img which src attrib is "data:application/octet-stream" with the file uploaded, same happens with pdf or any other non-valid extension.

**Comment by orthes** [comment]
I'll take a look at it.

**Comment by santiago-ervina** [comment]
FYI, I googled this and find some info: http://stackoverflow.com/questions/17451629/maxfilesize-and-acceptfiletypes-in-blueimp-file-upload-plugin-do-not-work-why
I tried the solution proposed, including also jquery.fileupload-process.js and then jquery.fileupload-validate.js to try to make it work with no success.

**Comment by orthes** [comment]
You were right. The upload plugin has some issues with a validation, so I implemented our own acceptFileType and maxFileSize validations. You don't have to include any new files.
