### ISSUE TITLE
Easier implementation to work with Image Uploads

### ISSUE THREAD

**Issue by pabloacastillo** [orthes/medium-editor-insert-plugin#190]
Hi there, im trying to implement this excellent work with wordpress and i found a possible upgrade to be done.

I finally got working the image upload with the native wordpress php asinc, and it works flawlessly, but i had to make a change to the source code.

In the [line 1790](https://github.com/orthes/medium-editor-insert-plugin/blob/master/dist/js/medium-editor-insert-plugin.js#L1790)

```javascript
var $el = $.proxy(this, 'showImage', data.result.files[0].url, data)();
```

I had to change it to:

```javascript
 var $el = $.proxy(this, 'showImage', data.result.data.url, data)();
```

My JS in the WP Plugin looks something like this:
```javascript
jQuery('#content2').mediumInsert({
	editor: editor,
	addons:{
		images: {
			fileUploadOptions:{
				url: '<?php echo admin_url();?>/async-upload.php',
				paramName: 'async-upload',
				formData: {	'_wpnonce': '<?php echo wp_create_nonce('media-form');?>','action':'upload-attachment' },
			}
		}
	}
});
```

Its there a better way to do this?

**Comment by orthes** [comment]
I will simplify custom modifications like this: see #178

**Comment by pabloacastillo** [comment]
Cool! Thanks! :+1:
