### ISSUE TITLE
Anchoring an uploaded image.

### ISSUE THREAD

**Issue by NoelBaron** [orthes/medium-editor-insert-plugin#195]
Hi there,

Is it possible to place the uploaded image into the medium editor as an anchor tag, piggy backing medium editor's "targetBlank:true" property? My goal is to launch the image in a new tab when the user clicks on it from non-editing view.

**Comment by orthes** [comment]
If your goal is to open an image in a new tab on click then you can wrap images into links only in non-editing view.

You can use something like this:

```javascript
$('.medium-insert-images').each(function (i) {
    $('img', this).each(function () {
        if ($(this).parent().is('a') === false) {
            $(this).wrap('<a href="'+ $(this).attr('src') +'" target="_blank" />');
        }
    });
});
```
