### ISSUE TITLE
JS error @v2.0.0 "this.hideButtons is not a function"

### ISSUE THREAD

**Issue by oznek** [orthes/medium-editor-insert-plugin#200]
I'm getting the error "this.hideButtons is not a function" at [core.js#L189](https://github.com/orthes/medium-editor-insert-plugin/blob/2.0.0/src/js/core.js#L189).

It appears to be related to the way Medium Editor extensions works (I was trying to figure out looking at [placeholder extension](https://github.com/yabwe/medium-editor/blob/d52099b9174144b27eb4e6fa051708c05836d6fa/src/js/extensions/placeholder.js).

Am I right? How can I help?

**Comment by j0k3r** [comment]
I already got a PR about that #199
