### ISSUE TITLE
Insert plugin buttons come along when serializing editor

### ISSUE THREAD

**Issue by okiuim** [orthes/medium-editor-insert-plugin#201]
Hi, I don't know if I am doing something wrong but when using the serialize() method of Medium Editor with the Insert plugin enabled the editor button divs come along in the html code ie. there are these elements in the end of the html of every instance

div:medium-insert-buttons
--a:medium-insert-buttons-show
--ul:medium-insert-buttons-addons

insert plugin version 2.0 and medium version 4.12.2

**Comment by okiuim** [comment]
Sorry guys, my bad, incorrect initalization.

**Comment by akashkamboj** [comment]
@okiuim i am having the same issue... how you resolved it?

**Comment by okiuim** [comment]
@akashkamboj I'm sorry, I don't remember. I build my own stuff instead of the plugin. Something to do with the initialization anyway which I did not do exactly as described in the documentation.
