### ISSUE TITLE
Can't upload images with customized path

### ISSUE THREAD

**Issue by KazuyaHara** [orthes/medium-editor-insert-plugin#202]
I'm using this plugin (really appreciate for this awesome work!!) on Ruby on Rails 4 and I defined upload path in applicaton.js like below. But it doesn't work. My app try to upload via upload.php as default. 

```
//= require jquery
//= require jquery_ujs
//= require jquery/dist/jquery.min.js
//= require medium-editor/dist/js/medium-editor
//= require handlebars/handlebars.runtime.min.js
//= require jquery-sortable/source/js/jquery-sortable-min.js
//= require blueimp-file-upload/js/vendor/jquery.ui.widget.js
//= require blueimp-file-upload/js/jquery.iframe-transport.js
//= require blueimp-file-upload/js/jquery.fileupload.js
//= require medium-editor-insert-plugin/dist/js/medium-editor-insert-plugin.min.js
//= require jquery-ui
//= require tag-it
//= require materialize-sprockets
//= require_tree .

$( document ).ready(function(){
  $('.editable').bind('input propertychange', function() {
    $("#article_" + $(this).attr("data-field-id")).val($(this).html().replace("#{params[:files]}", "url"));
  });
})

$(function () {
  $(".editable").mediumInsert({
    editor: editor,
    addons: {
      images: {
        fileUploadOptions: {
          url: 'upload_image',
          acceptFileTypes: /(.|\/)(gif|jpe?g|png)$/i
        }
      }
    }
  });
});
```

Is there anything wrong?

**Comment by orthes** [comment]
This is strange. When I try it, it works correctly. What versions of medium-editor and the plugin do you use?

**Comment by KazuyaHara** [comment]
I use Medium-Editor v2.0.0 and Medium-Editor-Insert-Plugin v1.0.0. It works correctly on development but doesn't work on production in Heroku. So I suspected this problem is caused by asset compile and I checked precompiled files. And js code I wrote above was included in compiled file (application-XXXXXXX.js).

**Comment by KazuyaHara** [comment]
It's caused by version of the plugin. "fileUploadOptions" must be used with 1.6.0 or later. Careless mistake :-(
