### ISSUE TITLE
UpdatePlaceholder issue

### ISSUE THREAD

**Issue by adamwalker196** [orthes/medium-editor-insert-plugin#203]
the line:

this.options.editor.placeholders.updatePlaceholder = this.editorUpdatePlaceholder;   

gives the error:
Uncaught TypeError: Cannot set property 'updatePlaceholder' of undefined

When I comment it out, it seems to work fine.

I am using this in a rails app, and installing medium through:
gem 'medium-editor-rails'

that is using medium editor version 4.2.0 as far as I can tell.

**Comment by j0k3r** [comment]
Could you take a look at #198 ? And tell us if it solve your problem.
