### ISSUE TITLE
Not able to hyperlink the paragraph with left align image

### ISSUE THREAD

**Issue by wwchen21227** [orthes/medium-editor-insert-plugin#204]
When i having image align to left and paragraph to right, i couldn't create link for the first word. Please refer to the attached image below. 

![bug](https://cloud.githubusercontent.com/assets/6290523/8492907/838e0c64-2184-11e5-8f3b-8e9fecaff0e0.png)

**Comment by j0k3r** [comment]
Thanks for the report, could you create a quick jsfiddle to reproduce the error ?

**Comment by wwchen21227** [comment]
In fact the screen captured was reproduced in the demo site http://linkesch.com/medium-editor-insert-plugin/.

**Comment by j0k3r** [comment]
You're right, in fact, as soon as an image is inserted before a paragraph, you can't make a link for the first world.
I guess it's a problem related to selection which shouldn't be well restored after submit the form with the url ..

**Comment by j0k3r** [comment]
We made some improvement on the link creation in MediumEditor. Could you try again with the latest MediumEditor version (ie 5.5.3) ? *You will need to force bower to fetch this version since medium-editor-insert-plugin restrict to the 4th version*.

**Comment by wwchen21227** [comment]
Thanks for the improvement, i have tested the MediumEditor latest version 5.6.2 and the link creation is working now.

**Comment by j0k3r** [comment]
@wwchen21227 thanks for the feedback !
