### ISSUE TITLE
Delete Script Should Have a HTTP Method Option

### ISSUE THREAD

**Issue by bertzzie** [orthes/medium-editor-insert-plugin#205]
Hello,

I am currently using your fantastic editor on a simple blogging app I'm developing. So far it's been great for me, but I have one little thing bugging me: 

The `deleteScript` is calling the URL with `POST` by default. 

Now this should be not a big deal, but I want to use `DELETE` because I want to directly delete the resource using the same URL as my insert, as a part of being a Restful app. Currently, this is impossible. 

Does this sounds like a good idea to you? If so, I may be able to help by sending a pull-request or two. Thank you very much.

**Comment by j0k3r** [comment]
That sound like a good idea, you're right.
But we need to avoid breaking change, so the best solution should be to:
- add an option (like `deleteScript`) called `deleteMethod` which should be at `POST` by default (to keep BC)
- add a condition in `Images.prototype.deleteFile` to use either `POST` or `DELETE` depending on the `deleteMethod` option

You can make an ajax `DELETE` request with jQuery like that:

```js
$.ajax({
    url: this.options.deleteScript,
    type: 'DELETE',
    data: { file: file }
});
```

**Comment by bertzzie** [comment]
Ok, I'm currently working on it. I can't assign myself at waffle.io though, but I'll send the pull request here as soon as I finished working.
