### ISSUE TITLE
Can't delete image - specific sequence of actions

### ISSUE THREAD

**Issue by Olgagr** [orthes/medium-editor-insert-plugin#207]
When image is added as a first element, sometimes it is not possible to delete it. What I do:

1. First I add image
2. Then I add two paragraphs below the image. Let's say that first have text "First" and second has text "Second".
3. Now I'm going to paragraph with "First" text and start to delete it from last letter.
4. When the whole paragraph is deleted and I still press Backspace, the image should also be deleted, but it's not.

**Comment by orthes** [comment]
Interesting, but you're right. It doesn't work for me either when I follow your steps.

**Comment by Olgagr** [comment]
Yes, if the first is a paragraph, then image, then a paragraph and another paragraph there is no problem. So it is something specific for image as a first node.

**Comment by Olgagr** [comment]
I also noticed that select all (cmd+A) is not working for this buggy case. Strange.

**Comment by Olgagr** [comment]
I played a little bit with this case and it seems like this is not the plugin bug. This is how contenteditable element behaves when you put the non-contenteditable element into it. Here is a code sample, without any script or plugin:

http://plnkr.co/edit/kT0CLKxNfd8w7XsNgtyU?p=preview

**Comment by orthes** [comment]
Thanks for investigating.
