### ISSUE TITLE
Errors on demo page

### ISSUE THREAD

**Issue by Olgagr** [orthes/medium-editor-insert-plugin#208]
I think on Friday the page was working but right now there are errors in console. When the system window is opened to pick the file there is TypeError:

```
Uncaught TypeError: Cannot read property 'ownerDocument' of undefined
```

When I clean up the whole editable area, add a new image and try to click below it to select the paragraph I get:

```
Uncaught IndexSizeError: Failed to execute 'getRangeAt' on 'Selection': 0 is not a valid index.
```

There are also some 404 errors for jquery.cycle2.min.js  and jquery.cycle2.center.min.js  files.

**Comment by orthes** [comment]
I don't know what happened. I updated the demo to the latest version and now it should work.
