### ISSUE TITLE
can not insert the content with image upload into Database, data is gone

### ISSUE THREAD

**Issue by mrtawans** [orthes/medium-editor-insert-plugin#209]
I working with CodeIgniter. when I submit Image is gone but Video embed is still stored in database except image and the images and thumbnail data is stored in Directory but no data in MySQL Database.

**Comment by orthes** [comment]
How do you get a content from the editor? You should use ```editor.serialize()``` function.

**Comment by wkurosawa** [comment]
@mrtawans have you solved this? 
I'm having a similar issue, still browsing through closed issues to see if I can find a similar problem.. 

I can upload images but they are only stored as HTML content if I try to input something in MediumEditor after uploads. 
Not sure if image insert is not triggering something right at MediumEditor.. must be some configuration error, I don't know :-/

**Comment by mitchnick** [comment]
@wkurosawa You can #254 for an example of the code which got it going for me.
