### ISSUE TITLE
Laravel csrf token

### ISSUE THREAD

**Issue by lotestudio** [orthes/medium-editor-insert-plugin#210]
I have troubles with csrf token when try implement plugin with Lravel.
Laravel need csrf token in every ajax request.
I use $ajaxSetup of jquery in that way:
`$.ajaxSetup({
                    headers: {
                        'X-CSRF-Token': 'xxxxxxx-csrf-token-key-xxxxx'
                    }
                });`

But this break loading json for embed media from medium.iframe.ly because of the X=CSRF-TOKEN header.
I try to post token field with posted data, but can't find the way to post the key when upload or delete image.
Any suggestions? Thanks!

**Comment by lotestudio** [comment]
I've found the solution.
Just changed 'oembedProxy' in emeds configration to my own route in laravel and return the content from medium.iframe.lu via curl.

**Comment by j0k3r** [comment]
If you found the solution, it's great :)

**Comment by kamdjouduplex** [comment]
Hello there,
I am experimenting this same error implementing the plugin in Laravel 5.5. but this time i am trying to upload images through `fileUploadOptions` but keeping getting this ajax error `POST http://localhost/my-app/public/posts/upload 405 (Method Not Allowed)` which usually mean the ajax request is missing the header csrf-token.
here is my javascript code to initiate the image insert: 
`
$(function () {
    $('.body-editable').mediumInsert({
        editor: bodyEditor,
         addons: {
            images: {
                preview: true, 
                fileUploadOptions: {
                    type: 'POST',
                    url: 'upload',
                    headers: {
                        'X-CSRF-TOKEN':  $('meta[name="csrf-token"]').attr('content')
                    },
                    dataType: 'json',
                },
            }
        }
    });
});
`
I pass the meta data in the header of my html like this:
`<meta name="csrf-token" content="{{ csrf_token() }}">`
and here is my Laravel route for that: 
`// upload image route for MediumInsert plugin
Route::post('upload', 'PostsController@upload');`

Please can someone help me on how to handle this to work ?
