### ISSUE TITLE
Hidde button and add custom class embed

### ISSUE THREAD

**Issue by laurentiustroia** [orthes/medium-editor-insert-plugin#213]
Hello, how can hidde button image ?

But if i want add some class on my oembed div what option need use ?

**Comment by j0k3r** [comment]
If you want to disable image addon, you just need to do that :

```js
$('.editable').mediumInsert({
    editor: editor,
    addons: {
        images: false
    }
});
```

There is no way at the moment to add a custom class to the embed div.

**Comment by laurentiustroia** [comment]
this remove all functionality, i want only to move right/left and remove images from my content but without functionality to add ...

I was go inside plugin to make only hidden with this:
` (depth0.display === false ? "style=\"display: none;\"" : "")` at line 16

and for embed add class on line 926 ( not tested yet ).

If have sugesstion who can hidde button let me know ...

**Comment by orthes** [comment]
You can try this:

```javascript
$('.editable').mediumInsert({
    editor: editor,
    addons: {
        images: {
            styles: false
        }
    }
});
```

**Comment by laurentiustroia** [comment]
orthes don't work your mettode i think only my hack is my solution for me
