### ISSUE TITLE
Hide Blinking Cursor

### ISSUE THREAD

**Issue by hakimihamdan88** [orthes/medium-editor-insert-plugin#214]
Hi, how can I hide the blinking cursor when adding image?

![Image]
(http://i.imgur.com/DrdaGQI.png)

**Comment by orthes** [comment]
Right now it's not possible, since we want give a user an option to continue writing if they decide not insert an image. We would have to save the caret position and restore it on key press. I'll mark this issue as an enhancement for the future reference.

**Comment by j0k3r** [comment]
This can be easily _hacked_.
We applied a `background-color: #fff` on `.medium-editor-insert-plugin .medium-insert-buttons .medium-insert-buttons-addons li` and it fixed the _problem_.

@orthes should I create a PR with that _fix_?

**Comment by orthes** [comment]
@j0k3r Good idea. Yes, you can create a PR.

**Comment by hakimihamdan88** [comment]
cool man
