### ISSUE TITLE
Drag and drop image

### ISSUE THREAD

**Issue by laurentiustroia** [orthes/medium-editor-insert-plugin#220]
When do drag and drop image from my pc, my image not insert good, I mean structure html is not same like i add when press button insert image.

If press insert image the structure is `<div><figure></figure></div>`
When drag and drop the structure is `<img>`

Who can prevent drag and drop or make it do same action like add image to add default structure ?

**Comment by j0k3r** [comment]
Which browser are you using?

I don't think this plugin handle drag'n'drop image. I guess that your browser handle it on its own and create a `<img>` node when you insert the image. I also guess that the `src` of this image isn't a file path but a `data:image`.

Also, this feature is enabled by default in Medium-Editor ([see the doc](https://github.com/yabwe/medium-editor#image-dragging-options)).

Maybe we can plan to handle drag'n'drop using the way we can upload an image.

@orthes thoughts? :)

**Comment by laurentiustroia** [comment]
I use Google Chrome  39.0.2171.95 and OS ubuntu 12 ...  thank you!
