### ISSUE TITLE
insert-plugin not working with editor.destroy() and then editor.setup() again

### ISSUE THREAD

**Issue by unkunus** [orthes/medium-editor-insert-plugin#224]
When switching between editor / textarea (raw/visual edit), the insert plugin produces an error:

Uncaught TypeError: Cannot read property 'enable' of undefined(anonymous function) @ medium-editor-insert-plugin.js:302j

JSFiddle: https://jsfiddle.net/ho4xtnfc/12/

there is a workaround to just hide and show the editor div or textarea , but then they need to be synced manually, as the insert plugin does not sync to the textarea automatically.

**Comment by is-blackhole** [comment]
Have same bug, any chance to fix?

**Comment by orthes** [comment]
Looks like this is fixed
