### ISSUE TITLE
Precompiled templates don't work with latest Handlebars runtime

### ISSUE THREAD

**Issue by litera** [orthes/medium-editor-insert-plugin#225]
I've downloaded latest version of Handlebars runtime library (4.0.2) to use medium editor insert plugin. but when I run my application I see this error in console window:

> Uncaught Error: Template was precompiled with an older version of Handlebars than the current runtime. Please update your precompiler to a newer version (>= 4.0.0) or downgrade your runtime to an older version (>= 2.0.0-beta.1).

Which version should I downgrade handlebars runtime to?

**Comment by j0k3r** [comment]
I think the 3.0.3 should be good.
Bower.json has `"handlebars": "~3.0.0",`.

**Comment by litera** [comment]
Yes. I was loading version by version and indeed 3.0.3 is the latest that can be used.
