### ISSUE TITLE
Insert plugin shouldn't add new elements to content editable

### ISSUE THREAD

**Issue by litera** [orthes/medium-editor-insert-plugin#226]
When I add Medium Editor Insert Plugin, this plugin adds its own toolbar markup directly to editable element, which is wrong because this addon becomes part of the content users are editing. Addon specific elements should be appended to the end of `body` or **anywhere outside of the editable element** (contenteditable sibling).

> **Note**: I've checked editor on Medium.com and their insert plugin doesn't add toolbar into editable content element either. Makes perfect sense to me.

**Comment by litera** [comment]
What I meant is that toolbar itself shouldn't be added to the content editable element. Result should of course be... That's natural.

**Comment by orthes** [comment]
If I remember correctly, we had it like this before, but we had some issues with positioning and multiple editors on the same page. Moving a toolbar to an editable element was the easiest solution at the time. But if you use editor's ```serialize()``` function, you should get a clean content without plugin's toolbar.

**Comment by litera** [comment]
@orthes I'm not using `serialize()` because I'm using Medium Editor in an Angular JS application that does the reading... Hence the problem.

**Comment by oosidat** [comment]
I'm experiencing a similar issue. In my attempt to use `angular-medium-editor`, `yabwe/medium-editor` and `medium-editor-insert-plugin` in my AngularJS app, the insert buttons getting injected into the content itself becomes a problem - currently, I'm looking into removing the buttons before I save the content, but in a "correct" (in my head) scenario, the buttons wouldn't be part of the content in the first place.

**Comment by litera** [comment]
@oosidat if you change the view ⇒ model functionality in your directive you can still use this extension. The thing is you have to change the way editor's content is read from the usual `innerHTML` to `editor.serialize()` because that's what this *extension* (if we can call it this way in the first place because it's more a jQuery plugin than an actual ME extension.
```javascript
// view => model
element.on("input change cut paste drop blur", function (evt) {
	// simple event throttling
	window.clearTimeout(eventOverlapping);
	eventOverlapping = window.setTimeout(function () {
		ngModelController.$setViewValue(scope.editor.serialize());
	}, 25);
});
```
In this example I've put the MediumEditor instance reference in `scope.editor`. In the directive code that you're using this is in the line 55:
```javascript
ctrl.$setViewValue(iElement.html());
```
You have to change it to:
```javascript
ctrl.$setViewValue(ctrl.editor.serialize());
```
Try it out. I thing that should do the trick of removing the insert DOM to be removed from content.

**Comment by oosidat** [comment]
@litera Thanks - I'll try it out!

I'm curious - in your directive, at what point in the controller/linking function do you initialize the insert plugin (by calling `angular.element(...).mediumInsert({...})`)?

**Comment by litera** [comment]
@oosidat Right after I create Medium editor.
```javascript
scope.editor = new MediumEditor({ ... });
$(element).mediumInsert({
    editor: scope.editor,
    addons: {
        images: {
            label: "<span class=\"icon photo\"></span>"
        }
    }
});
```
