### ISSUE TITLE
how to show input file change to opacity

### ISSUE THREAD

**Issue by uchuy77** [orthes/medium-editor-insert-plugin#227]
why input type file hidden to show, but opacity to 0, because in my safari version 5 not working show file dialog. button click upload image not work, in google chrome and firefox working..

why solution in safari 5?

**Comment by j0k3r** [comment]
Safari 5? Last version is Safari 9.
medium-editor is only compatible with Safari >= 8.

**Comment by uchuy77** [comment]
@j0k3r  thank's for reply..

yes i know.. last version safari 9, but i use plugin on work in safari 5. because safari 5 not support open file dialog, if file type not show, can u give me solution for open file dialog in this plugin?

thank's before..

**Comment by orthes** [comment]
As @j0k3r said, medium-editor itself supports only Safari >= 8. Safari 5 is 3 years old. We're not planning to add support to versions this old.
