### ISSUE TITLE
Backspace won't trigger delete event

### ISSUE THREAD

**Issue by ittikorns** [orthes/medium-editor-insert-plugin#228]
Hi,

I notice two things that won't trigger the delete event.

1. Insert an image and type some text into next lines
2. Keep pressing backspace from the line with text till the image is deleted by backspace (delete event is not trigger here)

OR

1. Insert an image and type some text into next lines
2. Select all and press backspace to delete (delete event is also not trigger)

Not sure this is intended to be done this way or it's a bug. 

Thanks

**Comment by nickground** [comment]
When will you fix this? :) I really need to have this bug fixed on my production sites. Thank you.

**Comment by j0k3r** [comment]
@nickground feel free to provide a fix :)
