### ISSUE TITLE
Issue with Image caption, Multiline support in Firefox

### ISSUE THREAD

**Issue by ryandh** [orthes/medium-editor-insert-plugin#230]
basically, press enter in the caption will cause wrong display in Firefox

1) create one image and add a caption, put something like 'hello' there, everything good. 
<img width="1242" alt="screen shot 2015-10-07 at 11 06 19 am" src="https://cloud.githubusercontent.com/assets/5561911/10346353/a55ce1e4-6ce3-11e5-949c-f3b6bdac9b73.png">
2) press enter at the end of hello, and type "world", got reverse response "dlorw". several empty figCaption elements were appended.
<img width="995" alt="screen shot 2015-10-07 at 11 08 45 am" src="https://cloud.githubusercontent.com/assets/5561911/10346400/e553256a-6ce3-11e5-8736-9ef2de040bf2.png">

Firefox: v33.1

**Comment by orthes** [comment]
Is this a bug in the plugin or in the editor itself? I see that you created a pull request in medium-editor repo. Can we close this issue here?

**Comment by ryandh** [comment]
yes, but of the media-edtor app

--  
RyanDH
"be yourself everyone else is already taken"
