### ISSUE TITLE
Save embed codes in database

### ISSUE THREAD

**Issue by themellwood** [orthes/medium-editor-insert-plugin#231]
When I save an embedded link from a textarea into the database, the code for the iframe is not saved, just the url inside p tags. Is this intentionally and is there any way I can just save the embed code?

![screen shot 2015-10-27 at 4 30 40 pm](https://cloud.githubusercontent.com/assets/6156319/10748739/182a7aa8-7cc8-11e5-9aa7-a2a8f9f2929e.png)

**Comment by orthes** [comment]
Thanks for the report. You're right. The editor changed the way it handles events. I tried to fix it with #216 but I ran into some problems with the PR. I'll try to fix it now and release it as soon as possible.

**Comment by orthes** [comment]
v2.1.0 was just released and it should fix this problem
