### ISSUE TITLE
Problem when embeding two or more iframes

### ISSUE THREAD

**Issue by joseqq** [orthes/medium-editor-insert-plugin#234]
When I  embed two or more viedeos or tweets and save the code in the database and then I try to render to show it, first video or tweets it is represented ok but second it is showed as code, I mean like <iframe width="560" height="315" src="https://www.youtube..... 
I appreciate that in database the data representing the iframes in the first video is like <iframe width..... but second video the symbol < is represented with other charset, like  & lt;iframe width="560" ...
Does someone if If it is recomended to embed to or more iframes or it is not allow ?? Thanks in advance.

**Comment by j0k3r** [comment]
Can you provide some code please?

**Comment by joseqq** [comment]
I do not do any specially (I think). I am testing with symfony and my route for adding a new comment has an action in the controller like: 

    public function nuevaPublicacionAction(Request $peticion) {

        $mensaje = new Mensaje();
        $formulario = $this->createForm(new MensajeType(), $mensaje);
        $formulario->add('publicar', 'submit');

        $formulario->handleRequest($peticion);

        if ($formulario->isValid()) {
            $this->get('session')->getFlashBag()->add('info', '¡Hecho! Tu publicación ya es accesible por todos');

            $em = $this->getDoctrine()->getManager();
            $em->persist($mensaje);
            $em->flush();

            return $this->redirect($this->generateUrl('mis_publicaciones'));
        }

        return $this->render(
                        'MensajesBundle:Default:nuevaPublicacion.html.twig', array('formulario' => $formulario->createView()));
    }

After this I can check the database (mysql) and I realese that at seconds iframe has the character < changed to \&lt; (always first one is correct !!).

If I update the column replacing the characters, then the post is render correctly. Then I do not know why is coming seconds iframes to the database wrongly. 

Thank you for your help.

**Comment by j0k3r** [comment]
And how do you display your form? Are you using MediumEditor on a textarea or a div?

**Comment by joseqq** [comment]
I was wondering about the controller, formtype,... and I found the problem at the html.twig code. As you guess I mistake with a  end tag ```</div>``` into my form. That break down all the magic. Thank your for your help.
