### ISSUE TITLE
Images are not inserted into DB

### ISSUE THREAD

**Issue by nickground** [orthes/medium-editor-insert-plugin#238]
Hi, everything is working fine. However, after uploading an image, I have to insert some texts. If I don't, the image are not saved into the database.

I use textarea. Please help. Thank you.

**Comment by orthes** [comment]
What version do you use? It shoud be fixed in ```2.1.0```

**Comment by nickground** [comment]
I use ver 2.1.0 :)

**Comment by orthes** [comment]
It looks like a problem in medium-editor and the way it handles textarea sync. I submitted a bug fix there.
