### ISSUE TITLE
Image uploading issue with generic handler in asp.net

### ISSUE THREAD

**Issue by kailashtandel** [orthes/medium-editor-insert-plugin#241]
Hello,
I am a .Net dev. So I don't understand how PHP works. So I modify upload.php to upload.ashx in medium-editor-insert-plugin.min.js file.
Now when I upload a file, trigger goes to my file but I am not able to get a file there.
Below is my handler code.

      public void ProcessRequest(HttpContext context)
        {
            context.Response.ContentType = "text/plain";
            context.Response.Expires = -1;
            try
            {
                HttpPostedFile postedFile = context.Request.Files["Filedata"];

                string savepath = "";
                string tempPath = "";
                tempPath = System.Configuration.ConfigurationManager.AppSettings["FolderPath"];
                savepath = context.Server.MapPath(tempPath);
                string filename = postedFile.FileName;
                if (!Directory.Exists(savepath))
                    Directory.CreateDirectory(savepath);

                postedFile.SaveAs(savepath + @"\" + filename);
                context.Response.Write(tempPath + "/" + filename);
                context.Response.StatusCode = 200;
            }
            catch (Exception ex)
            {
                context.Response.Write("Error: " + ex.Message);
            }
        }

Please suggest me how can I achieve this with my asp.net application.
Or suggest another way to I can upload image file to specific folder.

**Comment by orthes** [comment]
We're using [blueimp's jQuery File Upload Plugin](https://github.com/blueimp/jQuery-File-Upload) to hande all uploads. You can look to their documentation to see .NET examples: https://github.com/blueimp/jQuery-File-Upload/wiki#aspnet

**Comment by kailashtandel** [comment]
Thank you for your valuable suggestion.
