### ISSUE TITLE
Bugs when moving images: Cannot read property 'triggerInput' of undefined

### ISSUE THREAD

**Issue by nickground** [orthes/medium-editor-insert-plugin#243]
Hi, when I try to move an image, I can't move it easily. There is an error  at medium-editor-insert-plugin.min.js:10

Uncaught TypeError: Cannot read property 'trigger' of undefined

The demo also has this error. Can't move images. :) Please fix this. Thank you so much.

**Comment by j0k3r** [comment]
It looks like the demo isn't up to date. This `trigger` action [doesn't exist anymore](https://github.com/orthes/medium-editor-insert-plugin/blob/master/src/js/images.js#L67).

@orthes Could you update the demo page?

**Comment by orthes** [comment]
I fixed the problem and updated the demo.
