### ISSUE TITLE
Deletion of image failed because of CSRF token

### ISSUE THREAD

**Issue by jackyzhai** [orthes/medium-editor-insert-plugin#248]
For file uploads, we have fileUploadOptions, so that I can set 

    headers: {
        'X-CSRF-TOKEN': Cookies.get('X-CSRF-Token')
    }

However, it's not possible for deletions, any solutions? maybe something like fileDeleteOptions?

**Comment by j0k3r** [comment]
We do not have such option for the delete method. So yeah, it could be a great idea!

**Comment by jackyzhai** [comment]
Great thanks.

**Comment by ideadx** [comment]
Is this feature is coming? Be really great to pass tokens in request.

**Comment by jackyzhai** [comment]
@ideadx you can use my fork right now for this. https://github.com/jackyzhai/medium-editor-insert-plugin

**Comment by j0k3r** [comment]
@jackyzhai feel free to submit a PR !

**Comment by jackyzhai** [comment]
@j0k3r https://github.com/orthes/medium-editor-insert-plugin/pull/262  Thanks!
