### ISSUE TITLE
Images are not loaded.

### ISSUE THREAD

**Issue by ujinn** [orthes/medium-editor-insert-plugin#250]
Hello!

Why not persist the inserted picture?
Wrote an article, insert a picture, video. Retained.
Everything is there except pictures.
In the saved html code there is no img tag, no picture.
Where should it upload?
In what catalog?
Where to put the path?

**Comment by orthes** [comment]
We need more info. Can you reproduce your problem in https://jsfiddle.net/?

**Comment by ujinn** [comment]
Hello Pavel,

I've decided to abandon your plugin at the moment.
Not well described how to install it, how to put the path.
And even when I somehow installed it, he never wanted to save any picture or video.
I can't spend time repeating problem in https://jsfiddle.net/
All descriptions of errors in our correspondence.
However, I do not refuse completely from the help you.
The only thing I need step by step instructions how to correctly install the plugin and configure the path for saving images.
Look for similar instructions on the Internet and dig into the settings of your plugin I have no way.
At the same time, your plugin is very attractive and I would like to use it.
