### ISSUE TITLE
Inserting only an image isn't getting picked up by form submit

### ISSUE THREAD

**Issue by mitchnick** [orthes/medium-editor-insert-plugin#254]
Hey team, thanks for building an awesome plugin. I'm pretty close to having everything work as I would like, but keep on running into a really strange error when trying to only add an image and save the results. Not sure if it's an issue with the plugin or an issue on my end. Any help is greatly appreciated!

**Steps to produce error:**
I go to my edit form, add an image, wait for the server to save the image, add a data-id attribute on the image, and click save. The data submitted with the form does not include the newly added image. 

**Code:**
Below is my code.

```
App.Posts =
  init: ->
    editor = new MediumEditor('#post-content')
    editor = new MediumEditor('#post-content')

    editor.subscribe 'editableInput', (event, editable) ->
      console.log("***** editableInput Event *****")
      console.log(event)
      return

    $ ->
      $('#post-content').mediumInsert
        editor: editor
        addons:
          images:
            uploadCompleted: ($el, data) ->
              console.log("***** Image uploaded ****")
              photoId = data.result.id
              $img = $el.find('img')
              $img.attr('data-id', photoId)
      return
```

**And here is what is returned in the console:**
> ***** editableInput Event *****
> null
> ***** editableInput Event *****
> null
> ***** Image uploaded ****
> ***** editableInput Event *****
> null

When inspecting the page, the correct URL is added to the page: 
```
<p class="">Ohh, hi. Foob</p>
<div class="medium-insert-images medium-insert-active"><figure contenteditable="false">
    <img src="http://localhost:3000/system/photos/images/000/000/090/original/lambeau_2.jpg?1450665491" alt="" data-id="90">        
</figure></div>
```

I even tried to trigger changes manually on the input field with $("#post-content").trigger("change").

And for good measure, here is the content submitted with the form.
```
{"post"=>{"name"=>"Working it out", "content"=>"<p class=\"\">Ohh, hi. Foob</p><p class=\"\"><br></p>", "place_id"=>"4"}, "commit"=>"Update Post", "id"=>"833"}
```

**Comment by orthes** [comment]
Hi. How do you get the content? ```event``` variable doesn't store it. You should use ```editor.serialize()``` function: https://github.com/orthes/medium-editor-insert-plugin/wiki/v2.x-Getting-Started#getting-clean-content

**Comment by mitchnick** [comment]
Thanks @orthes, was able to get it going :) 

For anyone else looking, here is the code added: 
```
    $("#medium-wysiywg-form").submit ->
      allContents = editor.serialize()
      elContent = allContents[Object.keys(allContents)[0]].value
      $('#post-content').val(elContent);
      return true
```

From the code above, I removed the editor.subscribe 'editableInput' block and all console logs.
