### ISSUE TITLE
demo not working

### ISSUE THREAD

**Issue by klmdb** [orthes/medium-editor-insert-plugin#258]
Getting a 404

**Comment by j0k3r** [comment]
It works for me: http://linkesch.com/medium-editor-insert-plugin/

**Comment by klmdb** [comment]
Nope, nothing here:

Not Found
The requested URL /medium-editor-insert-plugin/ was not found on this server.


NOTE: not sure how it would make a difference but maybe my companies mitm ssl filtering breaks it somehow.

**Comment by j0k3r** [comment]
Works still great for me: http://hurl.eu/hurls/2ab5714e1761fee0afded64d2fe9e94436eb4d1b/ef047512510548f4bb6bf0d9791f4e3bba1ec797

Might be it's on your side :confused:

**Comment by satispunk** [comment]
Seems something worng with hosting provider or probably with russian rpovider

It is 404 for me (I am from Russia). But if vpn is used then it is ok. 
@klmdb Try browsec chrome extension and open that page.

**Comment by orthes** [comment]
Interesting. When I try VPN to change my IP address to Russian, it still works.

The code is hosted here on Github. I'll check with my domain registrar, if everything is OK on their side.

**Comment by orthes** [comment]
I've just checked it with my domain registrar and they are saying that everything is OK on their side.

**Comment by satispunk** [comment]
@orthes  Probably it is related to a specific internet provider that I use. That is weird but I have a workaround at least =)

**Comment by harriha** [comment]
Same problem here, cannot see the site, getting a 404 error page. I'm not behind any kind of suspicious firewall myself, rest of the web works fine. Not sure if it makes a difference, but the main http://linkesch.com/ gives me a generic WebSupport web hosting error page, too.

**Comment by orthes** [comment]
@harriha Thanks! Knowing that also the main linkesch.com website gives you an error helped me a lot. Can you try it one more time now?

**Comment by harriha** [comment]
@orthes Hey, yeah, now things seem to work - great! Good if I managed to help with this one and you got the issue figured out.

**Comment by klmdb** [comment]
Yep fixed here too. thx!
