### ISSUE TITLE
Non JQuery Version

### ISSUE THREAD

**Issue by oyeanuj** [orthes/medium-editor-insert-plugin#259]
Hi @orthes! This plugin looks great, and I was wondering if there are any plans at any point to do a non Jquery version of this? 

I am using the `react-medium-editor` and was wondering the best way to use this plugin and it seemed like using JQuery would add a lot of complications. Do you have any pointers on this?

**Comment by j0k3r** [comment]
We have planned to remove jQuery in the v3 (no ETA yet): https://github.com/orthes/medium-editor-insert-plugin/issues/177
