### ISSUE TITLE
Callback function when pressing Enter and disable embed option

### ISSUE THREAD

**Issue by nickground** [orthes/medium-editor-insert-plugin#260]
Hi,

I don't use oEmbed, may you show me how to have a callback function after pressing the Enter button.

I want to generate an image tag when pasting a url into the placeholder.

Is there any way to disable the embed button? (not showing it)

**Comment by orthes** [comment]
1. There is no callback function after pressing enter. You can use default JavaScript or jQuery events for that.
2. Disabling embeds:
```javascript
$('.editable').mediumInsert({
    editor: editor,
    addons: {
        embeds: false
    }
});
```
