### ISSUE TITLE
Delete Request is no longer been called

### ISSUE THREAD

**Issue by ideadx** [orthes/medium-editor-insert-plugin#265]
I updated the plugin and Delete Request is no longer been called when I remove the image?

deleteScript: '{!! action('XXX\JoyController@putSomeMethod') !!}',
deleteMethod: 'PUT',
fileDeleteOptions: {
_token: "{!! Session::getToken() !!}",
id : 1
},

**Comment by jackyzhai** [comment]
you need to use jquery options, such as:

                    deleteScript: '/images/delete',
                    deleteMethod: 'POST',
                    fileDeleteOptions: {
                        headers: {
                            'X-CSRF-TOKEN': Cookies.get('X-CSRF-Token')
                        }

**Comment by j0k3r** [comment]
Did you read the wiki about that new configuration https://github.com/orthes/medium-editor-insert-plugin/wiki/v2.x-Configuration ?

**Comment by ideadx** [comment]
@j0k3r @jackyzhai I have read the docs, and added the configuration above as @jackyzhai mentioned, but request has not been called.

**Comment by jackyzhai** [comment]
@ideadx it seems to work on my machine. can u post ur code here?

**Comment by ideadx** [comment]
here is a code: 

```
 deleteScript: '/post/method',
                            deleteMethod: 'POST',
                            fileDeleteOptions: {
                                headers: {
                                    'X-CSRF-TOKEN':  "{!! Session::getToken() !!}"
                                }
                               
                            },
```

Is there a way to log when method is running or response comes back?

similar to  
```
uploadCompleted: function ($el, data) {
                                console.log(data.result)
                            }
```

**Comment by jackyzhai** [comment]
@ideadx idk. I think j0k3r would have better info.
just curious. what syntax is this? 
{!! Session::getToken() !!}

**Comment by ideadx** [comment]
@jackyzhai Thats  Laravel Blade (a php framework)

**Comment by ideadx** [comment]
@j0k3r any idea to console log?

**Comment by j0k3r** [comment]
I'll have a look

**Comment by j0k3r** [comment]
Everything works great on my side.
I've tested on the example files ([from this repo](https://github.com/orthes/medium-editor-insert-plugin/blob/master/examples/index.html)) with that config:

```js
$(function () {
    $('.editable').mediumInsert({
        editor: editor,
        addons: {
            images: {
                deleteScript: 'delete.php',
                deleteMethod: 'POST',
                fileDeleteOptions: {
                    headers: {
                        'X-CSRF-TOKEN':  "TOKEN"
                    }
                },
                styles: {
                    slideshow: {
                        label: '<span class="fa fa-play"></span>',
                        added: function ($el) {
                            $el
                                .data('cycle-center-vert', true)
                                .cycle({
                                    slides: 'figure'
                                });
                        },
                        removed: function ($el) {
                            $el.cycle('destroy');
                        }
                    }
                },
                actions: false
            }
        }
    });
});
```

When I delete an image the ajax request is well sent with the additional token header:

![image](https://cloud.githubusercontent.com/assets/62333/12483682/b012d852-c056-11e5-9142-dde474e622fd.png)

Since it's an ajax request you might be able to debug it from your browser.

**Comment by ideadx** [comment]
Here is my full code:

https://gist.github.com/ideadx/143b768d97ba4ef5f96d

Here is file upload:
<img width="1439" alt="screen shot 2016-01-22 at 2 41 59 pm" src="https://cloud.githubusercontent.com/assets/2369963/12502261/7fe1f080-c116-11e5-92b5-9ec56da77925.png">
when I remove this files (using backspace or delete), image get removed from content but no requests get fired.

**Comment by jackyzhai** [comment]
I've no idea why this doesn't work for u. J0k3r may have better info. 
However, one thing you can do is to set up a br here and see what's wrong. It's basically just jquery ajax request.
https://github.com/orthes/medium-editor-insert-plugin/blob/adb9e9d7e3a0d0af582c33a3f5e698c3e4f95198/dist/js/medium-editor-insert-plugin.js#L1923

**Comment by j0k3r** [comment]
@ideadx did you try to remove all option related to delete to use default one and see if the ajax request is launched?

**Comment by j0k3r** [comment]
_sorry I double clicked on the wrong place_

**Comment by ideadx** [comment]
@j0k3r I have try removing all default options but the issue is still the same!

**Comment by ideadx** [comment]
I tried 4 different requests
````

1. Set default options
fileDeleteOptions: {
    headers: {
         ''X-CSRF-TOKEN':  "TOKEN"
    }
},

2. Remove token option
fileDeleteOptions: {
    headers: {
         // 'X-CSRF-TOKEN':  "TOKEN"
    }
},

3.
fileDeleteOptions: {
    //headers: {
         // 'X-CSRF-TOKEN':  "TOKEN"
    //}
},

4.
//fileDeleteOptions: {
//    headers: {
         // 'X-CSRF-TOKEN':  "TOKEN"
  //  }
//},

```

**Comment by j0k3r** [comment]
One last idea, what happen if you try to delete an image that is **already** in the dom? I mean an image that you didn't just uploaded.

**Comment by ideadx** [comment]
Same issue. Let's say I upload images, save the content and try to remove
it, nothing happens.

**Comment by j0k3r** [comment]
I'm out of idea.
:wave:  @orthes, we need your help

**Comment by ideadx** [comment]
@j0k3r Which version of jQuery you are using?  I am using: 2.1.4

**Comment by ideadx** [comment]
@orthes

**Comment by orthes** [comment]
@ideadx When you say that you use backspace or delete, do you mean that you select image first and then press one of those two buttons? Or do you place caret after the image and then press backspace? Because it is a known issue that deleting image together with text doesn't trigger the plugin's delete function (#228).

But if you're selecting an image by clicking on it first, then it should work. I tried it myself and it also works for me. 

The one last thing that remains here to do is to dive into the code and find out where it fails for you. Is `keydown` event triggered? Is `Images.prototype.removeImage()` called? Is `Images.prototype.deleteFile()` called after that? And finally, why the hell `$.ajax()` is not called?

**Comment by ideadx** [comment]
OMG!

I was doing  Second: place caret after the image and then press backspace to delete image which doesn't work. 

but I just selected image and try to delete and event did trigger. Oh Lorde....

**Comment by ideadx** [comment]
@j0k3r @orthes

**Comment by ideadx** [comment]
I think thats a critical issues (228). When you writing content  after the image and then press backspace to delete image is a natural scenario.

**Comment by ideadx** [comment]
@j0k3r @jackyzhai @orthes Thanks boys.
