### ISSUE TITLE
Uploading high quality image slows down typing

### ISSUE THREAD

**Issue by anilmaurya** [orthes/medium-editor-insert-plugin#267]
When user uploads high quality image(6mb-10mb) then writing posts slows down because image is reloaded on each keystroke.

![screen shot 2016-01-21 at 4 06 06 pm](https://cloud.githubusercontent.com/assets/1912864/12478108/34f612d0-c059-11e5-8988-769550e6e502.png)

Steps to reproduce:
1. open http://linkesch.com/medium-editor-insert-plugin/
2. upload hight quality image > 6 mb
3. start typing

Reason for this behaviour:

Image is reloaded because editor is `clone` on each keystroke. https://github.com/orthes/medium-editor-insert-plugin/blob/master/src/js/core.js#L180

To solve this Issue, I removed clone and modified function:

```
Core.prototype.editorUpdatePlaceholder = function (el) {
        var contents = $(el).children()
            .not('.medium-insert-buttons').contents();

        if (contents.length === 1 && contents[0].nodeName === 'BR') {
            this.showPlaceholder(el);
            this.base._hideInsertButtons($(el));
        } else {
            this.hidePlaceholder(el);
        }
    };
```

Let me know if you are willing to accept PR for this.

**Comment by orthes** [comment]
Great! Thanks for finding and investigating this problem. Please submit a PR with the fix.
