### ISSUE TITLE
Trying to set this up on a Meteor project, insert button not displaying.

### ISSUE THREAD

**Issue by sanders4069** [orthes/medium-editor-insert-plugin#269]
This is a Meteor.js project, and I downloaded the 'citizenkevin:medium-editor' package to get the .js and .css files for this project. The medium-editor works with the inline toolbar, but these medium-insert scripts are not working for some reason. I am not getting the (+) icon to appear on my web page, from what I can tell its because the the css class "medium-insert-active" is not showing up in any < p > tag.  

Anyone else run into this problem? Let me know if you have any thoughts :/

Thanks!

**Comment by j0k3r** [comment]
This package `citizenkevin:medium-editor` looks really old to me ...
I think you should better ask the guy behind this package.

**Comment by sanders4069** [comment]
Perhaps. I might need to figure out out to make my own Meteor package from scratch, maybe this one is just outdated.
