### ISSUE TITLE
Insert image as base64

### ISSUE THREAD

**Issue by JonasJonny** [orthes/medium-editor-insert-plugin#270]
Hi there.
Is it possible to insert a photo as base64 without upload to server?

**Comment by orthes** [comment]
Just set `uploadScript` to `null`. Look at our demo: http://linkesch.com/medium-editor-insert-plugin/ It uses base64 without server upload.

**Comment by JonasJonny** [comment]
Seems like it's not working properly.
POST text is without any img tag.
At the demo */upload.php script is still called.

**Comment by JonasJonny** [comment]
This https://github.com/orthes/medium-editor-insert-plugin/issues/254#issuecomment-166482149 helps me find a solution how to change textarea text before form POST submit. Thanks @mitchnick
---
@orthes 
```
    Core.prototype.triggerInput = function () {
        if (this.getEditor()) {
            this.getEditor().trigger('editableInput', null, this.el);
        }
    };
```
I guess function above should call medium-editor.js "updateInput" after image is inserted but
`updateInput: function (target, eventObj)` is not reached

**Comment by orthes** [comment]
I can't replicated your problem. It works for me correctly. Can you recreated it in https://jsfiddle.net/ ? Thanks.

**Comment by jomarbarnobal** [comment]
Good @orthes 
i use carrierwavebase64 and and set uploadScript to null but still see this 

jquery.js:9664 POST http://linkesch.com/medium-editor-insert-plugin/upload.php 405 (Method Not Allowed)

even in the demo is this normal ?

**Comment by injectless** [comment]
Same problem here!
Setted uploadscript to null and it's still doing it.

**Comment by JonasJonny** [comment]
```
<form id="mediumEditor" ...
  <textarea name="text" id="text" ...


$("#mediumEditor").submit(function() {
  var allContents, elContent;
  allContents = editor.serialize();
  elContent = allContents[Object.keys(allContents)[0]].value;
  $('#text').val(elContent);
  return true;
});
```

**Comment by EugeneSnihovsky** [comment]
@orthes Hello. Maybe you can help me with same problem? For now ** uploadScript** is deprecated and when I set **fileUploadOptions.url === null** - nothing changed. Image is set as url to blob
