### ISSUE TITLE
Changing src attribute after upload

### ISSUE THREAD

**Issue by MartinMalinda** [orthes/medium-editor-insert-plugin#273]
So I'm using the uploadCompleted() hook and it works great. Problem is, If I place a code like this there:
```
img.attr('src', response.thumbnailUrl)
```

It's of no use, because some other logic in the plugin code replaces the src yet again, with the regular response.url. 

So far I could come up only with some setTimeout(() => {...}, 200) hack which works, but feels dirty.

I know I could just switch the values on the server, but I'd like to avoid that solution if possible.

**Comment by orthes** [comment]
Thanks for reporting this. I've found the problem and a fix is on it's way.
