### ISSUE TITLE
Using MediumInsert with Require.js

### ISSUE THREAD

**Issue by msoledade** [orthes/medium-editor-insert-plugin#276]
First of all, we love the plugin and what it can do.

However, I looked over all the issues on Github, good ol' Google and couldn't find anything about the problem we're facing. The plugin, when used in a traditional RequireJS AMD structure, simply won't work. We tried it all, but either we have problems with the jquery.ui.widget module or we get the "Handlebars is not defined" error dispatched from the templates.js file.

Reading through the plugin docs, we found out that the jquery.ui.widget was a namespace problem and we fixed it, but we just can't get rid of the Handlebars error.

Are there any examples on how to use the plugin in a RequireJS structure? Thanks!

**Comment by orthes** [comment]
Can you reproduce your problem on https://jsfiddle.net/? I've successfully used the plugin with RequireJS in the past and I don't remember needing any special configuration.

**Comment by msoledade** [comment]
It is a huge project based on PHP with multiple views, but I can reproduce the RequireJS structure and the JS file which imports the exported ID for medium insert.

So this is the simplified version of our requireJS bootstrap with the shim config -- I removed a lot of libraries to make it easier to read, left only the ones related to jQuery and Handlebars.

![captura de tela 2016-02-10 as 14 03 49](https://cloud.githubusercontent.com/assets/1319498/12952853/2b8f5dea-cfff-11e5-9d1d-669a1806ff7f.png)

This is the JS file that requires the plugin, along with MediumEditor.

![captura de tela 2016-02-10 as 14 06 31](https://cloud.githubusercontent.com/assets/1319498/12952924/857d7012-cfff-11e5-9763-54290715b1c8.png)

Finally, this is the error happening.

![captura de tela 2016-02-10 as 14 07 23](https://cloud.githubusercontent.com/assets/1319498/12952984/b4f8dd7c-cfff-11e5-9e8a-043d205d91ca.png)

We found out the plugin requires handlebars runtime and we're already using handlebars. Does this have any impact?

Thanks for the quick reply.

**Comment by orthes** [comment]
Yeah, you need to require `handlebars.runtime.min`.

**Comment by msoledade** [comment]
Well, still not working though. Changed all the platform Handlebars to handlebars.runtime and it still throws the Exception. Any chance I can take a look at some boilerplate just to make sure the team here isn't missing anything? And thanks again for the reply :+1:

**Comment by orthes** [comment]
On my project I used something like this. I shimmed also handlebars to export as Handlebars. Maybe that's the trick.

```javascript
require.config({
    shim: {
        handlebars: {
            exports: 'Handlebars'
        },
        'medium-editor-insert-plugin': {
            deps: ['jquery-sortable', 'blueimp-file-upload']
        }
    },
    paths: {
        jquery: '../bower_components/jquery/dist/jquery',
        backbone: '../bower_components/backbone/backbone',
        underscore: '../bower_components/lodash/dist/lodash',
        handlebars: '../bower_components/handlebars/handlebars.runtime.min',
        'medium-editor-insert-plugin': '../bower_components/medium-editor-insert-plugin/dist/js/medium-editor-insert-plugin',
        'medium-editor': '../bower_components/medium-editor/dist/js/medium-editor.min',
        'jquery-sortable': '../bower_components/jquery-sortable/source/js/jquery-sortable-min',
        'blueimp-file-upload': '../bower_components/blueimp-file-upload/js/jquery.fileupload',
        'jquery.ui.widget': '../bower_components/blueimp-file-upload/js/vendor/jquery.ui.widget',
        'jquery.iframe-transport': '../bower_components/blueimp-file-upload/js/jquery.iframe-transport',
        Sortable: '../bower_components/Sortable/Sortable.min',
    }
});
```

```javascript
define([
    'jquery',
    'underscore',
    'backbone',
    'medium-editor',
    'Sortable',
    'medium-editor-insert-plugin',
], function ($, _, Backbone, MediumEditor, Sortable) {
    var IndexView = Backbone.View.extend({
        el: 'body',

        initialize: function (options) {
            var editor = new MediumEditor('#content');

            $('#content').mediumInsert({
                editor: editor
            });
        }
    });
});
```

**Comment by msoledade** [comment]
That's odd... I forgot including the handlebars shim in my print, but it is there! Well, I'll keep trying here. Thanks for sharing your code.

**Comment by msoledade** [comment]
Well, it worked in the end. However, we had to assign the Handlebars variable to the window scope, doing

`window.Handlebars = Handlebars`

I'm thinking two things here:

1. Shouldn't the plugin follow the AMD structure internally, specifically in the `templates.js` file?
2. Shouldn't the plugin consider the project can be already using Handlebars? Our problem here was the conflict between our global `Handlebars` variable exported by our shim and the `Handlebars` variable being used in the precompiled templates. Maybe changing the variable name to `HandlebarsRuntime`?

Sorry if I'm talking nonsense. Thanks!

**Comment by orthes** [comment]
That's interesting. I was able to use the plugin on my project without this hack.

But your points are correct. For the future we're planning to get rid of as much dependencies as possible and move to pure JS (without jQuery, Handlebars, etc.). We have no ETA yet: #177

**Comment by msoledade** [comment]
Thank you very much!
