### ISSUE TITLE
Image upload button doesn't work

### ISSUE THREAD

**Issue by THE-Beck** [orthes/medium-editor-insert-plugin#278]
Image upload button doesn't work in Android 4.4.2(default browser). Also in Safari (5.1.7)

> Pretty much huge mess on mobile

**Comment by orthes** [comment]
Yes, mobile devices are not officially supported either by us or [medium-editor](https://github.com/yabwe/medium-editor/tree/5.14.2#browser-support) itself. When medium-editor adds support, we'll follow.
