### ISSUE TITLE
Support for jQuery File Upload's deleteURL

### ISSUE THREAD

**Issue by noctivityinc** [orthes/medium-editor-insert-plugin#280]
The new format for the response for jQuery Upload includes a ```deleteUrl``` for the image.  It makes sense that that url should be set, if returned, as the URL to use when deleting an image.

**Comment by orthes** [comment]
I don't see `deleteUrl` documented anywhere. We're not using jQuery File Upload Plugin for deleting files. We have our own `deleteScript` option: https://github.com/orthes/medium-editor-insert-plugin/wiki/v2.x-Configuration#images-options

What would be an advantage to use jQuery File Upload Plugin's `deleteUrl` instead?

**Comment by noctivityinc** [comment]
You can see it here:

https://github.com/blueimp/jQuery-File-Upload/wiki/Setup#using-jquery-file-upload-ui-version-with-a-custom-server-side-upload-handler

In a RESTFul API the delete call for an object is a DELETE method call to ```/resource/:id``` but you dont know the ID until after you have created the object, which is why using the deleteURL returned from the server makes more sense.

Ive actually implemented this in my own version of your plugin and it works well.  Sorry I didnt fork it but didnt have the time.  I can post the code if you would like.
