### ISSUE TITLE
Facebook height strange behavior

### ISSUE THREAD

**Issue by rodrigojv** [orthes/medium-editor-insert-plugin#285]
When I insert a Facebook post, it seems like the FB.XFBML.parse() call tries to resize the iframe height after it has been displayed.

The result is that with some facebook posts, I end up with a height that causes a gap to be displayed between the post and the text that follows the post.

In the example below Facebook inserted a span with a height that is 'bigger' than the content of the iframe, so `<p>Some more text</p>` is displayed in the bottom of the page, and there is a big gap between the post and the last paragraph.
```
<div id="editor-body">
<p class="">Contenido</p>
<div class="medium-insert-embeds">
   <figure>
      <div class="medium-insert-embed">
         <div id="fb-root"></div>
         <div class="fb-post fb_iframe_widget" data-href="https://www.facebook.com/tecmundo/posts/994695247274983" data-width="550" fb-xfbml-state="rendered" fb-iframe-plugin-query="app_id=1484466181839826&amp;container_width=650&amp;href=https%3A%2F%2Fwww.facebook.com%2Ftecmundo%2Fposts%2F994695247274983&amp;locale=es_LA&amp;sdk=joey&amp;width=550">
            <span style="vertical-align: bottom; width: 550px; height: 4659px;">
            <iframe name="f1e9c9c10c" width="550px" height="1000px" frameborder="0" allowtransparency="true" allowfullscreen="true" scrolling="no" title="fb:post Facebook Social Plugin" src="http://www.facebook.com/v2.1/plugins/post.php?app_id=1484466181839826&amp;channel=http%3A%2F%2Fstaticxx.facebook.com%2Fconnect%2Fxd_arbiter.php%3Fversion%3D42%23cb%3Df25fc64744%26domain%3Dlocalhost%26origin%3Dhttp%253A%252F%252Flocalhost%253A8000%252Ff63919fd8%26relation%3Dparent.parent&amp;container_width=650&amp;href=https%3A%2F%2Fwww.facebook.com%2Ftecmundo%2Fposts%2F994695247274983&amp;locale=es_LA&amp;sdk=joey&amp;width=550" style="border: none; visibility: visible; width: 550px; height: 4659px;" class="">
            </iframe>
            </span>
         </div>
   </figure>
   </div>
   <p class="">Some more text.</p>
</div>
```

Has anyone had a similar problem before?

**Comment by orthes** [comment]
Can you reproduce this problem on https://jsfiddle.net/?

**Comment by rodrigojv** [comment]
I can't. Facebook tries to execute some JavaScript that is blocked by jsfiddle.

"VM365 xd_arbiter.php?version=42:1 Uncaught SecurityError: Failed to set the 'domain' property on 'Document': Assignment is forbidden for sandboxed iframes."

Here is the jsfiddle: https://jsfiddle.net/tyLthcpr/

**Comment by orthes** [comment]
I couldn't reproduce the problem. It works for me correctly. But if it's like you said that:

> it seems like the FB.XFBML.parse() call tries to resize the iframe height after it has been displayed

... Then you should report it to Facebook. We don't do anything with embedded iframes once we insert them.
