### ISSUE TITLE
textarea value not updated after image inserted / manipulated

### ISSUE THREAD

**Issue by quape** [orthes/medium-editor-insert-plugin#287]
I'm using this plugin with medium-editor on a textarea which is normally updated every time I type something in the editable.

Unfortunately, the textarea is not updated when I insert or manipulate an image using that plugin, so `editor.subscribe("editableInput")` gets called but with the old content.

What's the reason and how to solve it?

**Comment by orthes** [comment]
How do you retrieve the content? This works for me correctly:

```javascript
editor.subscribe('editableInput', function (event, editable) {
    console.log(editor.serialize());
});
```

**Comment by quape** [comment]
I do the same but it's not triggered after I have inserted an image.

**Comment by orthes** [comment]
Can you reproduce your problem on https://jsfiddle.net/?

When I try it on our [demo page](http://linkesch.com/medium-editor-insert-plugin/), it works.
