### ISSUE TITLE
Use AWS ManagedUpload

### ISSUE THREAD

**Issue by nikkwong** [orthes/medium-editor-insert-plugin#289]
I would love to be able to use this plugin with something like ```AWS.S3.ManagedUpload```. 

I can overwrite the ```add``` and ```showImage``` functions but I'm not sure how to plug in to progress events if I'm not using blueimp's native XHR object.

Any ideas?

Thanks.

**Comment by orthes** [comment]
We're using [jQuery File Upload](https://github.com/blueimp/jQuery-File-Upload) for uploading. You can use it to upload to S3 on server. Look here and search for S3 - https://github.com/blueimp/jQuery-File-Upload/wiki
