### ISSUE TITLE
New embed option

### ISSUE THREAD

**Issue by psypersky** [orthes/medium-editor-insert-plugin#290]
Hi, i made a new embed option for translating iframes into the original url when serializing the html
i named it "removeEmbedOnSerialization" (maybe i need a better name), if you think this could be added  to the lib i can improve the names and document it and make the appropriate PR. :)

https://github.com/psypersky/medium-editor-insert-plugin/commit/2cad52cd601bba74724a1fec9f734b53773031a5

**Comment by j0k3r** [comment]
IMO this is a good idea to have this option on board :+1: 
This means we'll have to re-embed all url when editing the content again. Like looping on all embed url and call embed function to build the iframe again, right?

Maybe name it `replaceEmbedByUrlOnSerialization` or `useEmbedUrlOnSerialization`.

**Comment by orthes** [comment]
Maybe we should have an option to choose between your behavior and the current one introduced by @nleush here: #277
