### ISSUE TITLE
Uncaught TypeError: $file.fileupload is not a function

### ISSUE THREAD

**Issue by reeveyew** [orthes/medium-editor-insert-plugin#294]
<img width="839" alt="screen shot 2016-04-02 at 22 45 59" src="https://cloud.githubusercontent.com/assets/9221973/14229191/bfac7172-f924-11e5-81c3-3b58bd716466.png">

Everything is working well (including embeding youtube videos) but not images.

When I click the upload image icon, I'll get the error:
medium-editor-insert-plugin.js:1630 Uncaught TypeError: $file.fileupload is not a function

**Comment by reeveyew** [comment]
my bad. imported the wrong file

**Comment by mikebronner** [comment]
I'm getting the same error midway through the project ... can you provide more details as to which file was wrong and how you corrected it? Im browserifying the npm package, and it **should** pull in all its dependencies, so not sure what I'm doing wrong. Thanks!
