### ISSUE TITLE
JS error after image selection in file finider: TypeError: c.process is not a function

### ISSUE THREAD

**Issue by mulaiko** [orthes/medium-editor-insert-plugin#295]
Hi @orthes ,

I get "TypeError: c.process is not a function" in my web console once I select an image to upload. Any pointers on how I can resolve this?

Thanks

**Comment by orthes** [comment]
I've never encountered this problem. Can you reproduce it on https://jsfiddle.net/?

**Comment by j0k3r** [comment]
This issue is fairly old and there hasn't been much activity on it. Closing, but please re-open if it still occurs.
