### ISSUE TITLE
Editor Hangs While Uploading Bigger Images (Size wise)

### ISSUE THREAD

**Issue by ankur0890** [orthes/medium-editor-insert-plugin#296]
Uploaded an Image of 15 MB and editor gets hanged or behaving very slowly. You can check the same on demo page itself.Any idea why this is happening?

**Comment by orthes** [comment]
Yes, I've recently discovered this bug myself. The bug has two parts - one is in the plugin and one in medium-editor. I've fixed both here https://github.com/orthes/medium-editor-insert-plugin/pull/291 and here https://github.com/yabwe/medium-editor/pull/1022

All those fixes are in master and will be released soon. I'll release new version of the plugin right now, so you can use the fixed version immediately. I'll talk to medium-editor guys and we'll release it too.

**Comment by ankur0890** [comment]
Thanks @orthes :) Will let you know after integrating :)

**Comment by orthes** [comment]
I've released v2.2.3 just now: https://github.com/orthes/medium-editor-insert-plugin/releases/tag/2.2.3

You should see huge improvement even without the medium-editor fix.

**Comment by ankur0890** [comment]
@orthes Hi, applied the patch and still editor hangs. I am uploading image of appx 15 MB. Applied both patches ( editor and plugin ) to local code. Can you please update the demo with the latest version so that I can check if its my code that's causing the issue or plugin code?

**Comment by orthes** [comment]
Ok. I'll update our demo later today. But remember to build dist files for medium-editor, because master branch doesn't have latest changes built. So even if you use master branch, you're still using old dist files. We're building dist files only when releasing a new version.

**Comment by ankur0890** [comment]
@orthes yup tested using new dist files. Checking with the App server if some issue on their side. Meanwhile please let me know when you update the demo. Thanks

**Comment by orthes** [comment]
I updated our demo to the latest version: http://linkesch.com/medium-editor-insert-plugin/

**Comment by ankur0890** [comment]
@orthes 404 on demo page

**Comment by orthes** [comment]
Github has some issues: https://status.github.com/messages

I also had 404 for a while. Now it works.

**Comment by ankur0890** [comment]
@orhanveli  It still not working. Its getting hanged for big images. Can you please try to write something after uploading big image

**Comment by orthes** [comment]
The bug is in medium-editor. My bugfix wasn't released yet. When you try to profile it you will see that on every keystroke medium-editor's `Events.updateInput` is called and it takes really long time when huge images are being uploaded. It has nothing to do with the plugin at this point.

I've fixed the editor and I've cut this lag time to half, so the editor is usable during upload.

<img width="1071" alt="screen shot 2016-04-05 at 13 58 34" src="https://cloud.githubusercontent.com/assets/312938/14280987/999292d2-fb36-11e5-802f-565cd2a9653d.png">
<img width="949" alt="screen shot 2016-04-05 at 13 58 51" src="https://cloud.githubusercontent.com/assets/312938/14280986/999216d6-fb36-11e5-9c89-bb21d5bdc875.png">

**Comment by orthes** [comment]
medium-editor v5.15.1 containing the fix has been just released: https://github.com/yabwe/medium-editor/releases/tag/5.15.1

**Comment by ankur0890** [comment]
@orthes  thanks for  your help but still in no luck :( Again its getting stuck a lot. Needs to restrict the Image size I think for production use

**Comment by ankur0890** [comment]
Soved this issue. Instead of showing base64,We can use blob url and on upload replace that with the server url. Base64 url takes lot of time for big images on browser that's why it's hanging thr editor.

**Comment by keligijus** [comment]
@ankur0890 I'm experiencing the same. Would you be able to share your implementation?

@orthes do you think medium-editor is going to deal with this? It seems that a lot of actions and other plugins are dependant on `Events.updateInput` and they're not going to throttle it. Should we make a PR for replacing base64 with Blob Url?
