### ISSUE TITLE
How to remove the insert buttons

### ISSUE THREAD

**Issue by reeveyew** [orthes/medium-editor-insert-plugin#297]
When I'm saving the content (text & images) to database, the medium-insert-buttons came along too! Wonder how to remove them?

`<div class="medium-insert-buttons" contenteditable="false" style="left: 15px; top: 273px; display: none;">
    <a class="medium-insert-buttons-show">+</a>
    <ul class="medium-insert-buttons-addons" style="display: none">
            <li><a data-addon="images" data-action="add" class="medium-insert-action"><span class="fa fa-camera"></span></a></li>
            <li><a data-addon="embeds" data-action="add" class="medium-insert-action"><span class="fa fa-youtube-play"></span></a></li>
    </ul>`

The above chunk appears in every article, although it's hidden, I don't think it should be in the database tho. Any idea? Thanks!

**Comment by orthes** [comment]
Duplicate: #23
