### ISSUE TITLE
how to use with npm?

### ISSUE THREAD

**Issue by zhaoyao91** [orthes/medium-editor-insert-plugin#304]
Now the npm package `medium-editor-insert-plugin` is gone, I don't konw how to use it with npm.
More, looking through this doc, I found it difficult to install this package with so many dependencies.

**Comment by orthes** [comment]
We've never been published on npm yet. But starting the nest release, we'll finally be: https://github.com/orthes/medium-editor-insert-plugin/pull/300

If you've found medium-editor-insert-plugin on npm, it wasn't official.

Regarding dependencies, I started working on vanilla JS version without any dependencies: https://github.com/orthes/medium-editor-insert-plugin/issues/177. I hope I'll be able to publish some sneak peak soon.

**Comment by orthes** [comment]
[v2.3.0](https://github.com/orthes/medium-editor-insert-plugin/releases/tag/2.3.0) was just released and we're finally on npm: https://www.npmjs.com/package/medium-editor-insert-plugin

**Comment by TrkiSF2** [comment]
@orthes ahoj, unfortunately this plugin is kind of impossible to use with npm and webpack. Spent several hours with it. The package dependencies are not loaded properly and using hacks like adding alias for webpack to resolve them is just a hacky way of doing it and at the end it didn't even helped. Did you try to set it up using npm? Let me know if you want me to report an issue with more info.

**Comment by orthes** [comment]
@TrkiSF2 Nazdar! Webpack problems are completely my fault. I haven't tested it properly. It should be fixed now in v2.3.2. I've also added a page to our documentation regarding webpack: https://github.com/orthes/medium-editor-insert-plugin/wiki/v2.x-Using-with-webpack

Let me know if it helped.

**Comment by TrkiSF2** [comment]
@orthes I run into an issue following the page you linked. Do you have any idea?

![screenshot from 2016-04-26 11 25 13](https://cloud.githubusercontent.com/assets/3595242/14813412/d93636ac-0ba1-11e6-8e52-38de5f959b19.png)

      "dependencies": {
            "medium-editor-insert-plugin": "^2.3.2",

     "devDependencies": {
         "imports-loader": "^0.6.5",
         "webpack-dev-server": "^1.9.0",
         "jsx-loader": "^0.13.2"
      }

config builder:

        module: {
            loaders: [
                {
                    test: /\.js$/,
                    loader: 'jsx?jsx-control-statements/jstransform'
                },
                {
                    test: /\.jsx$/,
                    loader: 'jsx-loader?insertPragma=React.DOM&harmony'
                },
                {
                    test: require.resolve("blueimp-file-upload"),
                    loader: "imports?define=>false"
                },
                {
                    test: require.resolve("medium-editor-insert-plugin"),
                    loader: "imports?define=>false"
                }
            ]
        },

After lunching webpack-dev-server with fresh installation of node_modules 

**Error: Cannot find module 'blueimp-file-upload'**

**Comment by orthes** [comment]
Hm. Looks like webpack can't find `blueimp-file-upload` in `node_modules` folder. Can you make sure that the `blueimp-file-upload` is installed? It should be installed as one of the plugin's dependencies.

**Comment by TrkiSF2** [comment]
yes it's a node module inside of medium-editor-insert-plugin.

**Comment by TrkiSF2** [comment]
@orthes any idea?

**Comment by TrkiSF2** [comment]
@orthes what npm, webpack version are u using? I tried to play with it again today and now I am running on webpack 1.13.0 and npm 3.8.7 now the loading ... almost works.

When I click to choose the picture from the computer I get: "Uncaught TypeError: undefined is not a function"

![screenshot from 2016-04-28 20 20 30](https://cloud.githubusercontent.com/assets/3595242/14896584/be2708c6-0d7e-11e6-904f-58086e84d342.png)

**Comment by TrkiSF2** [comment]
I hope I won't sound rude but what's the point of coupling this PLUGIN with a templating library? This whole thing contains like 3 buttons...

It doesn't make any sense imo... to make templates like images-fileupload.hbs ? 

![screenshot from 2016-04-28 20 42 21](https://cloud.githubusercontent.com/assets/3595242/14897599/03e8d9d0-0d83-11e6-9ac6-d92e88d464e5.png)

Is there any benefit I am overlooking ? :)

**Comment by orthes** [comment]
I'm using webpack v1.13.0 and npm v3.7.3 without any errors.

Using Handlebars was bad decision at the beginning. To understand that you need to go back to year 2013 when this project started. De facto default and the most popular framework was Backbone.js, so jQuery and Handlebars were part of huge number of projects. So people didn't mind that back then so much. Also in the beginning it looked like we gonna use much more HTML than we actually ended up using.

But the time has changed. I started working on completely rewritten version of the plugin here: https://github.com/orthes/medium-editor-insert-plugin/tree/3.0 - it has NO dependencies, it's pure ES6 transpiled with Babel.

**Comment by TrkiSF2** [comment]
Okay I see thx. Hmmm until then, do u have any idea what could be failing?

**Comment by orthes** [comment]
I'll get rid of handlebars and move HTML back to JS code directly. I'll try to do it this weekend. Or if you feel like it, you can give it a try yourself and submit a PR.

**Comment by TrkiSF2** [comment]
To be honest yesterday I tried again to setup handlebar loading and read official doc and try to do some stuff with it but without success so can't unfortunately invest more time into this sorry. If you can do that would be totally amazing! Som videl, ze si freelancer som si Ta pridal na FB robim na jednom vacsom projekte postavenom na reacte tak teoreticky ti viem dohodit nejaku pracu riesenu cez hodinovku ak chces :)
