### ISSUE TITLE
Disable H1, H2, quotes on embed's captions

### ISSUE THREAD

**Issue by psypersky** [orthes/medium-editor-insert-plugin#308]
Hello, i've been trying to disable those options on captions but im not sure of how to do it.
Could some one with more experience on the codebase point me in the right direction? Thanks.

**Comment by orthes** [comment]
Do you want to disable whole toolbar or just some buttons? Either way, right now it's not possible, and you'll have to override medium-editor. You can take a look here: https://github.com/orthes/medium-editor-insert-plugin/blob/2.2.4/src/js/core.js#L70 and here: https://github.com/orthes/medium-editor-insert-plugin/blob/2.2.4/src/js/core.js#L187 and see how we extend the editor. You'll have to change logic of toolbar depending on a context you're displaying it in.
