### ISSUE TITLE
File to import not found or unreadable: bootstrap

### ISSUE THREAD

**Issue by jomarbarnobal** [orthes/medium-editor-insert-plugin#309]
after install in rails 4.2 im having this error
any work arround ?

thanks

**Comment by j0k3r** [comment]
Which error?

**Comment by orthes** [comment]
We're not providing code for backend. We're using [blueimp's jQuery-File-Upload](https://github.com/blueimp/jQuery-File-Upload) which handles the upload. Take a look there and see if somebody ran into to the same problem as you.

**Comment by charlietag** [comment]
@jomarbarnobal 
It's not about medium-editor-insert-plugin or blueimp-jquery-file-upload. It's about jquery-sortable....
Only solution for this is workaround as following....
https://github.com/johnny/jquery-sortable/issues/193

```
It really looks that is tied to some bootstrap variables/files.

The only workaround that worked for me was editing _base.sass, commenting boostrap import and setting those un-initialized variables.

// @import bootstrap
$linkColor: blue
$grayLighter: gray
$grayLight: gray
$grayDark: gray
Commenting references to $iconWhiteSpritePath variable.

And also editing application.js to reference bootstrap files already included on vendor folder

//= require "./vendor/jquery"
//= require "./vendor/jquery.color"
//= require "./vendor/bootstrap-switch"
//= require "./vendor/bootstrap-scrollspy"
//= require "./vendor/bootstrap-dropdown"
//= require "./vendor/bootstrap-button"
Not the best solution I guess, but it allowed me to keep using it.
```
