### ISSUE TITLE
Full width banner images

### ISSUE THREAD

**Issue by mulaiko** [orthes/medium-editor-insert-plugin#311]
I'd like to have the option to stretch the image to the full width of the page.
Is this planned for a future release? Is there some other additional plugin I can use to achieve this?

Thank you for the work you have done on this library.

Cheers
Mulaiko

**Comment by orthes** [comment]
It's piece :cake:. Those image styles are meant to be extended. You can add your own like this: 

```javascript
$('.editable').mediumInsert({
    editor: editor,
    addons: {
        images: {
            styles: {
                wide: {
                    label: '<span class="fa fa-your-icon"></span>'
                }
            }
        }
    }
});
```

Example: https://github.com/orthes/medium-editor-insert-plugin/blob/gh-pages/index.html#L155

**Comment by mulaiko** [comment]
Hi @orthes

Thanks for your reply.

I think I may have worded my initial comment incorrectly.

What I'm asking for is the actual "full width image stretch" functionality. I want to be able to embed an image that then can be stretched to the full width of the page.

Cheers

**Comment by orthes** [comment]
I understand. There is no built-in functionality like this and there'll never be. The plugin is meant to be extended and you should add your own styles. There is no universal solution for this. Every website has it's own layout, etc. You have to create this yourself.

Just add a new style like I've shown you above. This will create a new icon in toolbar and when you click on it, it will add this class to image container: `medium-insert-images-wide`

This way you can use this class and style it as you want:

```css
.medium-insert-images-wide {
    width: 100%;
    // ...
}
```

The style will depend on your page layout.

**Comment by kargnas** [comment]
@orthes There is just a 'medium-insert-images' when image attached. A 'medium-insert-images-wide' class will added at least click the image alignment toolbar. (Maybe this is bug, need to create issue)
