### ISSUE TITLE
Usage with browserify

### ISSUE THREAD

**Issue by xar** [orthes/medium-editor-insert-plugin#319]
Hello,

really good work with plugin. I have only one question. How to use plugin with browserify. I have installed it via npm with dependencies. Then i required it as:
`var MediumInsert = require('medium-editor-insert-plugin');` .
I have also jquery on
`window.$ = require('jquery');` but i still get 
`Uncaught TypeError: $(...).mediumInsert is not a function`

**Comment by xar** [comment]
I managed to get it work:
`
var MediumEditor = require('medium-editor');
var Handlebars = require('handlebars');
global.jQuery  = require('jquery');
var sortable = require('jquery-sortable');
require('blueimp-file-upload');
require('medium-editor-insert-plugin')(jQuery);

var editor = new MediumEditor('.editable');
      $('.editable').mediumInsert({
                editor: editor
       });
`

But i'm not sure if it's correct way

**Comment by orthes** [comment]
I made some changes to our UMD setup in v2.3.2. You can check that out. I've also added a page to our documentation regarding webpack: https://github.com/orthes/medium-editor-insert-plugin/wiki/v2.x-Using-with-webpack. It should be helpful also for browserify.

Basically, what you should be able to do now is this:

```javascript
var MediumEditor = require('medium-editor');
var jQuery = require('jquery');
require('medium-editor-insert-plugin')(jQuery);
```

**Comment by mikebronner** [comment]
Hmm, I have been unable to get it to work in any fashion using webpack or browserify using Laravel Elixir, following the webpack instructions, or these, as close as possible. Version 3.0 seems to be a bit from finalized (it's throwing console errors), how far off do you expect it to be? I was able to get it to upload images, but not much more than that. Should I try using it, ignoring the console errors?
