### ISSUE TITLE
Any more information on the delete button URL?

### ISSUE THREAD

**Issue by CraigLovelock** [orthes/medium-editor-insert-plugin#322]
I have everything working and using S3 along with Laravel for my app. I have a routes set up for deleting images, but cant see how to link the delete button url to the selected image?

The docs just show 'delete.php' as the URL, before I start hacking my way through is there already some way of passing in an image attr or similiar to the delete url? Or how have others done it?

**Comment by orthes** [comment]
File name is sent along with the request: https://github.com/orthes/medium-editor-insert-plugin/blob/master/src/js/images.js#L577

If you need more, you can use `fileDeleteOptions` to extend/override default AJAX configuration.
