### ISSUE TITLE
video issues not storing in db

### ISSUE THREAD

**Issue by vimal-g** [orthes/medium-editor-insert-plugin#327]
i newly tried medium editor insert plugin when i paste video URL form YouTube its showing preview after i published its not showing video preview and also not saving in db. i am using chrome browser showing console like www-embed-player.js:612  XHR failed loading: GET "chrome-extension://fmfcbgdsogabcbclcofgddsadocippekhfcmgfjaswerer/cast_sender.js".i need to store data and video embed with thumbnail image

**Comment by orthes** [comment]
How do you save the content? You should use `editor.serialize()`
