### ISSUE TITLE
How to add code snippet 

### ISSUE THREAD

**Issue by nahid** [orthes/medium-editor-insert-plugin#330]
Its really awesome, I didn't find any process to add code snippet. How can I do it?

**Comment by orthes** [comment]
You can create your own addon for that: https://github.com/orthes/medium-editor-insert-plugin/wiki/v2.x-Custom-addons

The most important function is `CustomAddon.prototype.add` which is called when you click on the addon button. There you can do whatever you want.

**Comment by nahid** [comment]
Thank you so much
