### ISSUE TITLE
Impliment activity indicator?

### ISSUE THREAD

**Issue by mikebronner** [orthes/medium-editor-insert-plugin#335]
I didn't see any documentation in the wiki on how to best implement an activity indicator for upload and delete activity? I was hoping for some callback functions I could use that would be triggered when the upload or delete request is kicked off, and when they complete, to easily show and hide and spinner. Any thoughts?

**Comment by orthes** [comment]
Take a look here: https://github.com/orthes/medium-editor-insert-plugin/issues/369#issuecomment-238210060
