### ISSUE TITLE
Can we plugin to react?

### ISSUE THREAD

**Issue by jcalfee** [orthes/medium-editor-insert-plugin#338]
I'm using this component: [react-medium-editor](https://github.com/wangzuo/react-medium-editor/blob/6e1491aef56d1102cc3235637b61d2f618c0c2d5/lib/editor.js#L26) .. You can see on that line it assepts a pass-through `options` parameter.  So the question is:

Can your cool insert plugin be installed via Medium options.extensions?
`new MediumEditor(div, {options: extensions: {...}})`)

A side note:  I'm kind of at a dead-end.  We are confused as to how your inserting your `mediumInsert` function into the editor given the example:
```js
var editor = new MediumEditor('.editable');`
$('.editable').mediumInsert({editor: editor})
```

**Comment by jcalfee** [comment]
I think this works as follows: 
```js
    componentDidMount() {
        const dom = ReactDOM.findDOMNode(this);
        this.medium = new MediumEditor(dom, this.props.options);
        $(dom).mediumInsert({
            editor: this.medium
        });
    }
```

**Comment by Megasonic988** [comment]
How were you able to import mediumInsert into the react-medium-editor library?

**Comment by NeoHub** [comment]
@jcalfee Did you edit the `react-medium-editor` library to add support for `mediumInsert`? Or did you create your own react wrapper?

**Comment by jcalfee** [comment]
@NeoHub libraries were not edited.  Here is the [MediumEditor](https://github.com/steemit/condenser/blob/medium-editor/app/components/elements/MediumEditor.jsx) that we were working on at that time ..

**Comment by Heluwe** [comment]
@jcalfee Thanks

**Comment by nghoangduongse** [comment]
Hi @jcalfee
I want to add this to reactjs too, so can you help me with this issue?
I alway receive error .mediumInsert is not a function when i using that code

thank you

**Comment by bolahanna44** [comment]
i was able to integrate it with react using #https://github.com/orthes/medium-editor-insert-plugin/wiki/v2.x-Using-with-webpack

the only thing is in webpack.config.js use the following: 

```
module.exports = {
  entry: "./src/index.js",
  module: {
    loaders: [
      {
        test: require.resolve("blueimp-file-upload"),
        loader: "imports-loader?define=>false"
      },
      {
        test: require.resolve("medium-editor-insert-plugin"),
        loader: "imports-loader?define=>false"
      }
    ]
  }
};
```

instead of the following

```
module.exports = {
  entry: "./src/index.js",
  module: {
    loaders: [
      {
        test: require.resolve("blueimp-file-upload"),
        loader: "imports?define=>false"
      },
      {
        test: require.resolve("medium-editor-insert-plugin"),
        loader: "imports?define=>false"
      }
    ]
  }
};
```
