### ISSUE TITLE
Serialized content contains `<div class="medium-insert-images-progress"></div>`

### ISSUE THREAD

**Issue by jcalfee** [orthes/medium-editor-insert-plugin#341]
After an image upload, the serilized content still has a progress div in it:
```
const allContents = editor.serialize()
const elContent = allContents["element-0"].value
...
<div class="medium-insert-images-progress"></div>
```

**Comment by jcalfee** [comment]
2.3.2

**Comment by jcalfee** [comment]
Looks like this can be removed too:  ` class="medium-insert-images medium-insert-active"`

**Comment by orthes** [comment]
You can create a pull request with a fix. Just update this function to remove what's not needed: https://github.com/orthes/medium-editor-insert-plugin/blob/c49bc918e7317fd876315f179f811c51f397e238/src/js/images.js#L172

**Comment by gabrielpeixoto** [comment]
I tried to use the latest version of medium editor but I cannot got it to work. I tried all the versions but the only version that worked was the version 5.16.1.
