### ISSUE TITLE
Toolbar - How

### ISSUE THREAD

**Issue by injectless** [orthes/medium-editor-insert-plugin#342]
![screenshot_2016-06-29_18-18-41](https://cloud.githubusercontent.com/assets/12424545/16469172/f133210a-3e25-11e6-888e-348f987752f4.png)

Hi.
I'm trying to do something like above. I know medium-editor works with extensions, and this is one.. 
Tried to looked at the code, but with all the other libraries and all, I couldn't find what I need.

I need a custom toolbar for elements, like this plugin does so beautifully.
(I am writing a plugin for MathJax and Medium-Editor, I just need to know how can I show a toolbar when the user clicks the generated-PNG from MathJax and can re-edit it, but I got that cover)

Exactly like the image above, click any image and show a custom toolbar above them.
Thanks!

**Comment by orthes** [comment]
This is a question for medium-editor, not for this plugin. But you can create your own extension (custom-toolbar or whatever) and this extension would extend the built-in medium-editor toolbar, or you can duplicate the built-in toolbar and change what you need.

The first option is what I've done here - https://github.com/orthes/medium-editor-insert-plugin/blob/3.0/src/js/Toolbar.js - and the new toolbar is initialized here - https://github.com/orthes/medium-editor-insert-plugin/blob/c0de83cd002aead734d4f0df7912db4191edba38/src/js/addons/Images.js#L48
