### ISSUE TITLE
Closing in 3.0

### ISSUE THREAD

**Issue by injectless** [orthes/medium-editor-insert-plugin#344]
Hello again,
It's like the twentieth issue I open here, I'm starting to wonder if I came too far.

I traded my old bugs for a whole set of new ones.
^: not quiet, I still need help with the last issue.

I have the following situation using the new 3.0 branch:

![orthes1](https://cloud.githubusercontent.com/assets/12424545/16542581/fe4697f8-4084-11e6-8380-dec2bc2326cc.png)

Amazing, adding a image works. Just a tiny detail.
![orthes2](https://cloud.githubusercontent.com/assets/12424545/16542582/1c08c77a-4085-11e6-8af8-2d1401c985d6.png)

Ok, now I can't upload any more images.
Why?
![screenshot_2016-07-02_18-36-07](https://cloud.githubusercontent.com/assets/12424545/16542592/82d90708-4085-11e6-96ef-21cf071a6512.png)

You see, the tree is now attach to that single branch. It needs to die.
Now, like Eric Roth wrote: «You can be mad as a mad dog at the way things went, but when it comes to the end.. you have to let go».

![orthes3_tocut](https://cloud.githubusercontent.com/assets/12424545/16542611/c5aef880-4085-11e6-8663-30c47a232d64.png)

That element has to have a closer, otherwise the button to add more images won't show up.
I could use some help.

**Comment by injectless** [comment]
@orthes can you help me?
no one but you knows the code better.
please.

**Comment by orthes** [comment]
Related to this: https://github.com/orthes/medium-editor-insert-plugin/issues/343

Branch 3.0 is far from being ready. It's just a WIP.

**Comment by injectless** [comment]
I figured. I think I fixed the tree problem!
I'm going to test it 'cause it gave me trouble a few attempts ago.

I left you a message in the other issue, I need to know how to select the text, how to add it a class or something to the image to make it align. That's really important and it doesn't seem to be hard.

**Comment by injectless** [comment]
For anyone who might be in the same position as me, this fix it:
```
   addonClassNames.forEach(function (className) {
	                if (el.classList.contains(className) || _utils2.default.getClosestWithClassName(el, className)) {
	                    isAddon = true;
	                    return;
	                }
	            });
```

Now, what this does is completely remove the function @orthes added: The button will show always, even if you are writing text (which, with the code above, when you writing or the cursor is in a element which has text, the button won't show up).

For me, this is just fine.
