### ISSUE TITLE
Options table is cut off

### ISSUE THREAD

**Issue by jcalfee** [orthes/medium-editor-insert-plugin#346]
https://github.com/orthes/medium-editor-insert-plugin/wiki/v2.x-Configuration#general-options

![image](https://cloud.githubusercontent.com/assets/204121/16630245/3872d9b2-437f-11e6-8007-5dab12130fdd.png)

This is in recent versions of FF and Chrome.

**Comment by jcalfee** [comment]
One work around is to uncheck display: block:
![image](https://cloud.githubusercontent.com/assets/204121/16630329/8e9642ac-437f-11e6-849b-153c60c965f7.png)

**Comment by lauranjansen** [comment]
This is a result of the way github displays tables, not an issue with this project.

**Comment by jcalfee** [comment]
Ok .. Better work-around:  scroll right..  I did not see that scrollbar.
