### ISSUE TITLE
show custom UI when the file is not a valid format or exceeds the maximum size?

### ISSUE THREAD

**Issue by mage007** [orthes/medium-editor-insert-plugin#351]
I have a use case that needs to show customized UI popup when the file format is not valid or file size is too large. Currently the plugin only shows an alert box to show the invalid status.

Is there a way to do it?

Seems like File Processing Options in https://github.com/blueimp/jQuery-File-Upload/wiki/Options already provides the ability to add customized validation functions.

**Comment by orthes** [comment]
Duplicate: #350
