### ISSUE TITLE
Same Instagram embed only working first time

### ISSUE THREAD

**Issue by ankur0890** [orthes/medium-editor-insert-plugin#353]
Unable to embed the same instagram url twice.

Steps:
1. Embed same url twice
2. first one embed will generate iframe while second embed will not render iframe.
3. Works fine if you embed different urls.

<img width="684" alt="screen shot 2016-07-19 at 3 06 27 pm" src="https://cloud.githubusercontent.com/assets/1263424/16945446/be9cae30-4dc2-11e6-8300-ead30263701c.png">

**Comment by orthes** [comment]
This looks like an issue with instagram, not with this plugin. If you think otherwise, feel free to reopen this issue.
