### ISSUE TITLE
Custom Addon gives TypeError

### ISSUE THREAD

**Issue by IshavanBaar** [orthes/medium-editor-insert-plugin#354]
Does the Custom Addon feature still work? I don't understand how to do it. I have tried the [scaffolding code](https://github.com/orthes/medium-editor-insert-plugin/wiki/v2.x-Custom-addons), but the custom addon file (`test.js`) never gets called, and thus doesn't show up.

There is no documentation on how to make it called, but I figured the solution would be to add a line to `core.js`: 

```
    var pluginName = 'mediumInsert',
        defaults = {
            editor: null,
            enabled: true,
            addons: {
                images: true, // boolean or object containing configuration
                embeds: true,
                test: true // ADDED TO CALL THE CUSTOM ADDON 'TEST'
            }
        };
```
But `core.js` always gives a TypeError on `that.$el[addonName](options);` (line 291):

`Uncaught TypeError: that.$el[addonName] is not a function`

It seems that it can't find the `function(options) `of the new addon. The strange thing is that this happens even when I simply save images.js or `embeds.js` with another name!

What am I missing? Please help me!

**Comment by orthes** [comment]
You need to insert your new file to html. It looks like you haven't done that. Simple `<script src="PATH TO YOUR test.js"></script>` will do the trick.
