### ISSUE TITLE
Button position is incorrect with release 2.3.3

### ISSUE THREAD

**Issue by michalkopanski** [orthes/medium-editor-insert-plugin#358]
Hi Pavel (@orthes), we're using this plugin with [medium-editor](https://github.com/yabwe/medium-editor) and ever since release 2.3.3 (more specifically I think it's https://github.com/orthes/medium-editor-insert-plugin/pull/356), we have been getting incorrectly calculated `top` and `left` positions on the UI buttons.

We're using the bootstrap framework and the position of the editor container is set to `relative`. The CSS has not been modified since upgrading, and since the release, the button position is broken.

**Comment by orthes** [comment]
@michalkopanski thanks for reporting this problem. It's always better to test it on real life projects than on a few example applications or demo pages.

I think I fixed your problem. Please try using `master` and see if it helps. If yes, I'll release 2.3.4 with a fix.
