### ISSUE TITLE
Buttons are positioned incorrectly

### ISSUE THREAD

**Issue by george-norris-salesforce** [orthes/medium-editor-insert-plugin#361]
![image](https://cloud.githubusercontent.com/assets/17860864/17118364/17b20ef0-5275-11e6-802b-43f0fa673c64.png)

using v2.3.3

```
   const dom = $(".medium-editor-element");
    let medium = new MediumEditor(dom);
    medium.setContent("hello world");


    $(dom).mediumInsert({
      editor: medium
    });
```

also 
after image is uploaded..
![image](https://cloud.githubusercontent.com/assets/17860864/17126892/34df023a-52b6-11e6-8bc3-ee9c8b4c2cb2.png)

this + button is superimposes on the images right bottom side

**Comment by george-norris-salesforce** [comment]
container (Bootstrap) was setting container to position relative

**Comment by orthes** [comment]
This is not a bug, it's a feature. There were always problems with positioning + button under an image and since + button is connected to the image, I moved it to the right bottom corner.
