### ISSUE TITLE
Disable uploads not working 

### ISSUE THREAD

**Issue by george-norris-salesforce** [orthes/medium-editor-insert-plugin#362]
```
$(dom).mediumInsert({
      editor: medium,
      addons: {
        preview: true,
        captions: false,
        images: {
          fileUploadOptions: {
            url: null
          }
        }
      }
    });
```

still tried to upload

I'd like to disable all uploading and only display image as base65 in the editor. 

Others have set `uploadScript` to false to disable uploads, but that syntax is now deprecated syntax (also doesn't work..I've tried it too). 

**also there is an error when adding photos on your demo page**
![image](https://cloud.githubusercontent.com/assets/17860864/17146251/939668d4-5312-11e6-93cb-21e74479811b.png)

**Comment by orthes** [comment]
In #373 i sort of fixed it. Sort of... I removed default upload.php path for uploads, so we fallback to default jquery file upload behavior described here: https://github.com/blueimp/jQuery-File-Upload/wiki/Options#url:

> If undefined or empty, it is set to the action property of the file upload form if available, or else the URL of the current page.

So you're not able to disable upload at all. It will always be sent somewhere.

**Comment by bernardwolff** [comment]
Using a similar technique to orthes's third option described at https://github.com/orthes/medium-editor-insert-plugin/issues/369, I was able to make this work.


let images = $element.data('plugin_mediumInsertImages');

    images.add = function () {
      let $file = $('<input type="file">');

      $file.fileupload({add: function(e, data) { 
        let file = data.files[0];
        let reader  = new FileReader();
        let loadListener = (name) => {
          let result = {
              files: [{
                  url: reader.result,
              }]
          };
          images.uploadDone(null, {
            result: result
          });
          // set the upload progress to 1/1 (100%) which hides the progress bar
          images.uploadProgressall(null, {context: images.$el, loaded: 1, total: 1});
          images.core.triggerInput();
        };

        images.uploadAdd({target: null}, {autoUpload: false, files: data.files});

        reader.addEventListener("load", loadListener.bind(reader, file.name), false);
        reader.readAsDataURL(file);
      }});

      $file.click();
    };
