### ISSUE TITLE
Cannot create Custom Addon 

### ISSUE THREAD

**Issue by lipcanu** [orthes/medium-editor-insert-plugin#368]
I am trying to add a new addon. I am working with the provided template, but what is confusing to me is where in the code structure should I link the new addon to the Insert Plugin? 

Is it in core.js?

Adding it here gives an error:

```
 addons: {
                images: true, // boolean or object containing configuration
                embeds: true, 
                myaddon: true
            }
```

Can you please provide more documentation on that?

**Comment by orthes** [comment]
Probably duplicate: #354

You need to insert your new file to HTML and then initialize like you did.
