### ISSUE TITLE
How to remove the style bar 

### ISSUE THREAD

**Issue by Cryde** [orthes/medium-editor-insert-plugin#378]
Hi,

I want to know if it was possible to remove the style bar?
By default I center all the images ... So the style bar doesn't have any sens !

I tried this : 
```
  $('#editor').mediumInsert({
    editor: editor,
    addons: { 
      images: {
        captions: false, 
        styles: { 
          grid: null,
          wide: null,
          left: null,
          right: null,
        },
      }
    }
  });
```
But when I click on the image there is still the "style bar" that appear (empty)

Thank you in advance !

**Comment by j0k3r** [comment]
By _style bar_, you mean the toolbar to set image position?

**Comment by Cryde** [comment]
Yep

**Comment by orthes** [comment]
There's no option like this. Just try doing something like this in CSS:

```css
.medium-insert-images-toolbar {
  display: none !important;
}
```

**Comment by Cryde** [comment]
Thanks ! :)
