### ISSUE TITLE
Unable to edit image without div.medium-insert-images tag

### ISSUE THREAD

**Issue by Hoiy** [orthes/medium-editor-insert-plugin#380]
I tried to load some old posts content through
editor.setContent(post_content);

I am not able to edit `<img>` tag while medium-insert-images plugin. Manually wrapping them around `<div class="medium-insert-images">` would make them editable. My question is, what is the correct way to import these content without manually wrapping the `<img>` tags?

Furthermore, I found that inserting image through medium-insert-plugin would induce a `<div class="medium-insert-images">` around the image. I get my html output via
var allContents = editor.serialize();
var elContent = allContents["element-0"].value;

Another question: is it possible to strip these `<div>` tags?

**Comment by j0k3r** [comment]
My guess is that you need to add them when you plan to edit and remove them when you want to save content.
