### ISSUE TITLE
Moving from Dante editor 

### ISSUE THREAD

**Issue by akkias** [orthes/medium-editor-insert-plugin#382]
Hi,
I am currently using Dante editor for blog posts and for some reasons I found this editor is better than Dante so I wanted to move from it.
But I am facing difficulty with existing content while editing it, 
Could you please tell me how should I be cleaning up the existing HTML with this editor.

**Comment by j0k3r** [comment]
Could you please provide some code on how you tried to handle it?

**Comment by akkias** [comment]
I am just initialising the editor
For eg.

<div id="editor">
***raw HTML***
</div>

*--*

*Akshay SonawaneMobi ~ 9158 42 0989*

**Comment by orthes** [comment]
@akkias Please provide more info. What problems do you have specifically? Ideally, can you reproduce them on codepen, jsfiddle or similar service?
