### ISSUE TITLE
Successive calls to repositionToolbars()

### ISSUE THREAD

**Issue by JohnONeill** [orthes/medium-editor-insert-plugin#385]
Is there are reason that there are [two successive calls to repositionToolbars() within autoRepositionToolbars()](https://github.com/orthes/medium-editor-insert-plugin/blob/master/src/js/images.js#L636)?

**Comment by j0k3r** [comment]
To be sure toolbar is well positioned?
Just joking, I don't know :)

poke @orthes :point_up:

**Comment by orthes** [comment]
I don't really remember, but I remember that it was a workaround for some problem we had. If you remove one of the calls, I think it will break for some reason. Feel free to fix the underlaying problem if you want.
