### ISSUE TITLE
Toolbar not showing controls 

### ISSUE THREAD

**Issue by kailashtandel** [orthes/medium-editor-insert-plugin#386]
Hello,

I have implemented Medium editor in my one of blogging site.
It was working very good till last week. Last week suddenly toolbar stopped showing controls.
I just want to know anyone of you know the reason why this happened?

Please help me to solve this. see the snapshot attached.

This is not a browser specific issue, its not working in any browser.

![image](https://cloud.githubusercontent.com/assets/15960091/18550921/d9da4afc-7b73-11e6-9efd-22f4c09ebf06.png)

**Comment by j0k3r** [comment]
Did you include the css for FontAwesome?

**Comment by kailashtandel** [comment]
Yes I included,

**Comment by kailashtandel** [comment]
Got the solution.
Actually my site is running on HTTPS and the url I included was from HTTP.
So the file was not loading. Due to that I was facing the issue.
Thank you so much for making a wonder full editor... :)
