### ISSUE TITLE
Error on generating iframes (Youtube)

### ISSUE THREAD

**Issue by luisdalmolin** [orthes/medium-editor-insert-plugin#388]
Hi there, 

I'm getting an error when trying to insert youtube vídeos. I think there's a problem with the API used to generating the iframe's. Here it is an screenshot of my network console.

![screen shot 2016-09-22 at 9 19 47 am](https://cloud.githubusercontent.com/assets/403446/18747861/eaf1add0-80a5-11e6-881f-0692b8857878.png)

Is there a fix for that?

**Comment by j0k3r** [comment]
Looks like a problem on your side. It works great on the demo page: http://linkesch.com/medium-editor-insert-plugin/
From where are you testing?

**Comment by luisdalmolin** [comment]
It worked when I added the scripts individually on the page. I think there was a problem with the webpack build.

But thank you.
