### ISSUE TITLE
Insert plugin clears existing text on startup

### ISSUE THREAD

**Issue by forby** [orthes/medium-editor-insert-plugin#392]
Maybe this is a configuration issue on my end, but I haven't been able to find the answer so far.

Currently I have the medium plugin working fine for an existing set of editable forms.  When editing existing entries, the plugin will initialize _with_ the existing field content so you can continue to edit.

However when using the Insert plugin, the field's content is always immediately replaced with:

``` html
<p class="medium-insert-active">
    <br>
</p>
```

after initialization, despite the existing content in the editable field.  Even with the most basic recommended plugin configuration.

Has anyone else run into this, or found a way to keep this from happening?

[Plugin v2.4.0]

**Comment by forby** [comment]
I think I've traced it down to this:
```javascript
if (this.$el.children().length === 0) {
    this.$el.html(this.templates['src/js/templates/core-empty-line.hbs']().trim());
}
```
No matter what I try, `this.$el.children()` always returns an invalid prevObject instead of a list of the children, so the length always returns 0.  Anyone else experiencing this?

**Comment by orthes** [comment]
That's weird. I've never seen this bug before. Can you repro it on codepen, jsfiddle, or similar service?

**Comment by forby** [comment]
@orthes Sure thing! http://codepen.io/forby/pen/GjBQOq

**Comment by milansimek** [comment]
I encounter the same issue, with contenteditable div elements

**Comment by derrekbertrand** [comment]
I'm getting this on 2.4.1, any ideas?
