### ISSUE TITLE
The editor reference is not set when handling multiple fields

### ISSUE THREAD

**Issue by forby** [orthes/medium-editor-insert-plugin#393]
If there are multiple fields being used when setting up the plugin, only the first receives the 'editor' option reference. This will break the toolbar calls, or anything that uses Core.getEditor() for the subsequent fields.

Using the default setup like so with version 2.4.0:
```javascript
var editor = new MediumEditor('.editable');

// ...

$(function () {
    $('.editable').mediumInsert({
        editor: editor
    });
});
```

Live test-case: http://codepen.io/forby/pen/NRBNNj

**Comment by orthes** [comment]
Yep. That's really not a bug. Insert plugin needs to have a reference to an editor it's connected to. In your case it would be best to initialize editors and plugins in a loop, so one insert plugin is connected to one editor. So something like this should fix your problem:

```javascript
$(function () {
    $('.editable').each(function () {
        var editor = new MediumEditor($(this).get(0));
        $(this).mediumInsert({
            editor: editor
        });
    });
});
```

**Comment by forby** [comment]
@orthes This makes much more sense now with a few other things I was seeing. I think I wrongly assumed `mediumImsert` would work on a collection.  Sorry, I should have tried that first.  Thanks!
