### ISSUE TITLE
Question: Correctly managing deleted images in an edit setting

### ISSUE THREAD

**Issue by forby** [orthes/medium-editor-insert-plugin#394]
I guess I'm just having a hard time wrapping my mind around this process. If anyone has had to work around this successfully, I'm all ears. Here's the scenario:

We are using the insert plugin for inline images in a blog post type of page.  When creating, the script works great and images are being uploaded and stored on the server.  This works great as the content in the creation page has no reference on the database yet. We're not syncing automatically, changes are only by a submission action.

However, when _editing_ a user can modify the text or images and then abort (which is fairly expected).  But deleting an image with this plugin is made to immediately remove the file from the server, resulting in missing images if the edit is aborted.

But we also don't want to avoid managed-deletion of images.  Editing posts could lead to a lot of abandoned image overhead.

Any suggestions for managing input that has both async (images) and deferred (text) content?

Asking for a friend 😁

**Comment by bgaillard** [comment]
Hi, we do not do this for now but the process I think would do it is the following. 

* Never delete you images using the `deleteScript`
* On server side
    * At upload time always create a sub-directectory for each new uploaded file to prevent conflicts with files uploaded with the same names, for example `1/file-1.png`, `2/file-1.png`, `3/file-1.png`.
    * When the content of your text is saved (or the edits are aborted) make a diff between the image URLs present in the HTML content of the editor and the content of the file system, delete files which do not correspond to any URL in the HTML content.

The last problem could be that the user exists its browser in such a way you cannot consider its an "aborted event". In this case you can use a "last opened date" and "last update date" and create a CRON script which cleans images which are not "in sync" with the content if the "last opened date" and "last update date" it older in comparison with the current server date.

Hope this helps.

**Comment by forby** [comment]
@bgaillard thanks! I ended up with a kind of similar solution:

- no deleting with the `deleteScript`
- image filenames get a timestamp in the string to prevent overwriting duplicates
- images are always created in a temp directory that gets cleaned out with a nightly cron job. When a post is saved, related images are moved to a permanent location to avoid cleanup.

Seems to be working well so far. The temp images folder never grows to large over the course of a day. Thanks so much for getting back to me (I mean...er...my friend) 😅
