### ISSUE TITLE
Embed youtube video doesn't play

### ISSUE THREAD

**Issue by faustoct** [orthes/medium-editor-insert-plugin#397]
after embed youtube video it contains medium-insert-embeds-overlay that makes impossible to play video by clicking.

the workaround I found:
`$('.medium-insert-embeds-overlay').remove()`

Would be great have a method such as `cleanup()` but need to know everything should be removed right of the editor.

**Comment by AkinoLucas** [comment]
* This work for me: [Issue](https://github.com/orthes/medium-editor-insert-plugin/issues/23)
