### ISSUE TITLE
CSS class "medium-insert-embeds-selected" is included on the output of .serialize()

### ISSUE THREAD

**Issue by mrehayden1** [orthes/medium-editor-insert-plugin#406]
This adds an outline to any .medium-insert-embeds.

Might we drop all the styling classes from the output apart from ones used by the plugin to identify embedded content?

**Comment by Cryde** [comment]
I find a way to remove the unwanted content : 
```
function getContent() {
  const editorHtml = $('#editor').val(),
    contentNoButtons = $(`<div>${editorHtml}</div>`).find('.medium-insert-buttons').remove().end();
  return contentNoButtons.html();
}
```

It's a bit dirty but I don't have more ideas

**Comment by t-kanstantsin** [comment]
Hi, @Cryde 
can you explain where you put and how you use this function?
