### ISSUE TITLE
add custom class to img element

### ISSUE THREAD

**Issue by mete89** [orthes/medium-editor-insert-plugin#410]
Hi,

I want to add a class to img element and also change the src to data-src after I got image url from server.

change this
`<img src="https://xyz.com/xyz.png">`

to

`<img class="cld-responsive" data-src="https://xyz.com/xyz.png">
`
Is there any way of doing this with implemented methods?

**Comment by bernardwolff** [comment]
Something like this should work.

```
function handleUploadCompleted($el, data) {
	var file = data.result.files[0];
	var $img = $el.find('img');
	$img.attr('class', 'cld-responsive');
	$img.attr('data-src', file.url);
}
$('.mediumEditor').mediumInsert({
	editor: this.medium,
	addons: {
	  images: {
		uploadCompleted: uploadCompleted,
	  }
	}
});
```

**Comment by mete89** [comment]
thanks that solved my problem.
