### ISSUE TITLE
<p> insert after an image don't allow enter

### ISSUE THREAD

**Issue by mariochavez** [orthes/medium-editor-insert-plugin#416]
Hi,

I have found that when you insert an image a <p> tag is inserted after, that <p> is editable but don't accepts Enter or Shift+Enter, I see this with latest Safari and Chrome, does anyone have seen this issue?

https://github.com/orthes/medium-editor-insert-plugin/blob/e46a46f6f6929c36f2aa4d881066b10bddaf5e30/src/js/images.js#L273

**Comment by orthes** [comment]
Can't repro
