### ISSUE TITLE
how to use this plugin in vue2.x

### ISSUE THREAD

**Issue by SimonZhangITer** [orthes/medium-editor-insert-plugin#417]
I have tried use it in vue2.0,but got some error
![image](https://cloud.githubusercontent.com/assets/20501873/24182070/2219134c-0efa-11e7-99fe-d69d0a43dc07.png)

**Comment by avral** [comment]
The same error

**Comment by keligijus** [comment]
Hey, same problems here. For anyone who stumbles here, webpack related issue might help: https://github.com/orthes/medium-editor-insert-plugin/issues/324
