### ISSUE TITLE
ES6 Webpack error

### ISSUE THREAD

**Issue by avral** [orthes/medium-editor-insert-plugin#425]
For my application on VueJs I use es6 and webpak.

<img width="452" alt="screen shot 2017-05-25 at 15 49 38" src="https://cloud.githubusercontent.com/assets/10092436/26441236/4eb87eac-4162-11e7-9294-2f337d9e6d8f.png">

<img width="379" alt="screen shot 2017-05-25 at 15 49 48" src="https://cloud.githubusercontent.com/assets/10092436/26441398/e9383134-4162-11e7-91fb-6acab0341fd2.png">

And I get this error:

<img width="579" alt="screen shot 2017-05-25 at 15 58 18" src="https://cloud.githubusercontent.com/assets/10092436/26441454/0923f0d2-4163-11e7-8cf7-3b8e9bacc25f.png">

**Comment by orthes** [comment]
Take a look here: https://github.com/orthes/medium-editor-insert-plugin/issues/441
