### ISSUE TITLE
Image File is not uploading to the server.

### ISSUE THREAD

**Issue by jochop** [orthes/medium-editor-insert-plugin#431]
I am trying to upload my file to server , but the file is not sending to controller method. 
Here is my code:
 $(document).ready(function() {
            $('.editable').mediumInsert({
                
                editor: editor, // (MediumEditor) Instance of MediumEditor
                enabled: true,
                addons: {
                    images: {
                        fileUploadOptions: {
                        	 
                        	 type: "POST",
                        	 paramName:"files[]",
                        	 multipart: true,
                            url: '${pageContext.request.contextPath}/a/{storeurl}/upload/image.json',
                            acceptFileTypes: /(\.|\/)(gif|jpe?g|png)$/i
                            	
                        }
                    }
              
                }
          
                
                
            });
        });

**Comment by orthes** [comment]
Not enough info. Can you repro on jsfiddle/codepen/our demo page?
