### ISSUE TITLE
The given range isn't 

### ISSUE THREAD

**Issue by ant000151** [orthes/medium-editor-insert-plugin#432]
Hi, we are integrating Medium Editor and the Insert Plugin inside our product.My English will be little poor, sorry for that.
 
While adding a link we are getting an error **"The given range isn't"**  in the line number 367.
` e.setStart(g.childNodes[0], d), e.collapse(!0), f.removeAllRanges(), f.addRange(e)`.

We Don't know why it happens. Please help me to find out the solution.

**Comment by orthes** [comment]
The error is coming from medium-editor, not from this plugin. Post it to their issues here: https://github.com/yabwe/medium-editor/issues
