### ISSUE TITLE
Editing an article with an insert

### ISSUE THREAD

**Issue by Arnopikar** [orthes/medium-editor-insert-plugin#435]
Hi! 

I try to install medium-editor with your plugin but i have a problem when editing an article. Loading the page stops for one minute and ends with an error. A script is problematic and i have to stop it to access the editor (which works perfectly after that).

![capture du 2017-07-23 14-40-23](https://user-images.githubusercontent.com/29689518/28499545-b92eb268-6fb8-11e7-8a26-e83b0f9ac998.png)

The problem is on all browsers i've used (Chrome and Firefox). Unlike Chrome will stop only and does not say that a script problem. I compared with an article that has no insertion and then everything works. 

I have the last release of medium-editor and medium-editor-insert-plugin (5.23.1 and 2.4.1).

No ideas on the origin?

**Comment by orthes** [comment]
@Arnopikar Can you repro it on our demo page, or jsfiddle/codepen? Until then it's near to impossible for me to reproduce.
