### ISSUE TITLE
image upload not consistent between drag/drop and insert plugin

### ISSUE THREAD

**Issue by jimmymain** [orthes/medium-editor-insert-plugin#439]
If an image is uploaded using the insert plugin via the "add" button on a new paragraph, the image is uploaded to the server, and the url returned.

If an image is dragged on the editor, it is embedded using base64 encoding.

The drag image workflow should be consistent with medium-editor-insert-plugin.
Perhaps this will require the default drag/drop functionality in medium-editor to be overridden somehow by the insert plugin.

**Comment by orthes** [comment]
@jimmymain The thing is that the "add" button is coming from this plugin, but the drag-n-drop functionality is coming from medium-editor itself. Support for dragging was added to medium-editor after the insert plugin was created and those 2 are not compatible. I wanted to add support for drag-n-drop to the plugin for the longest time and make it compatible with the existing solution medium-editor has, but I didn't have time.
