### ISSUE TITLE
The div that holds the buttons (.medium-insert-buttons) is inside .editable!

### ISSUE THREAD

**Issue by AmineBelais** [orthes/medium-editor-insert-plugin#440]
How can I remove the div that holds the buttons add, camera and YouTube icons (the div with the class .medium-insert-buttons) from inside the .editable div. Which ends up stored with the typed text in the database.

I'm using Medium Editor with textarea.

Can I have the .medium-insert-buttons div appear near the .editable div (just like the default behavior) without being inside of it?

**Comment by orthes** [comment]
https://github.com/orthes/medium-editor-insert-plugin/issues/21
https://github.com/orthes/medium-editor-insert-plugin/issues/23
https://github.com/orthes/medium-editor-insert-plugin/issues/64
https://github.com/orthes/medium-editor-insert-plugin/issues/123
