### ISSUE TITLE
Is there a way to modify the response data?

### ISSUE THREAD

**Issue by paltman** [orthes/medium-editor-insert-plugin#443]
I don't have complete freedom to modify the response.  I can see where I can modify the variable from `files[]` to whatever my server is expecting on the upload but don't see where I can hook in and transform the response data.  Surely that is possible and I'm just missing some key point in the documentation.

Can you point me where the hook is?

Thanks!

**Comment by orthes** [comment]
@paltman I don't think we have a built-in hook for this. Obviously ideal would be to modify the backend response on backend. If that's not possible, take a look at [jquery upload plugin](https://github.com/blueimp/jQuery-File-Upload/wiki) and see if they support something like this. If not, take this plugin, fork it and customize it to match your needs.

**Comment by deslittle** [comment]
Is this not related to #410 ?
