### ISSUE TITLE
Relative position on container breaks positioning of buttons

### ISSUE THREAD

**Issue by paltman** [orthes/medium-editor-insert-plugin#445]
I have experienced this in Bootstrap 4 using containers like `.row > .col` or `.card`.

I'm not sure of the correct solution but have been able to fiddle with some margins of the button container to move it where i want.

See this Pen: https://codepen.io/paltman/pen/WZXXMb

**Comment by orthes** [comment]
@paltman That's totally ok. Actual implementation depends on an environment you're using the plugin in, so fiddling with margins is a correct approach.
