### ISSUE TITLE
Embed not working on an ssl enabled server

### ISSUE THREAD

**Issue by sobha-sudheesh** [orthes/medium-editor-insert-plugin#448]
Medium insert pulgin enbed not working in an ssl enabled server.In chrome it is throwing  net::ERR_INSECURE_RESPONSE error.Please help

**Comment by portablepage** [comment]
I ran into the same issue, but fixed it by switching to noembed.com:

`
embeds:{
	oembedProxy: 'https://noembed.com/embed?url='
}
`
Hope that helps!

**Comment by orthes** [comment]
https://iframely.com/ graciously gave us their oembed API for demo and testing purposes for free. But you're expected to configure the plugin to use whatever oembed service provider you choose and if you choose iframely, you should signup with them and use your own API key. And of course, iframely do support SSL. So you should never use http://medium.iframe.ly in a production anyways.

**Comment by robin-epicswan** [comment]
Great, thanks a lot !
