### ISSUE TITLE
Editor keeps contenteditable attributes after save

### ISSUE THREAD

**Issue by NARKOZ** [orthes/medium-editor-insert-plugin#454]
Tested on master with #437 applied. All images and embeds keep `contenteditable` attributes after save.

**Comment by orthes** [comment]
How do you get editor content? You should always use [editor.serialize()](https://github.com/yabwe/medium-editor/blob/b1b0e87eb5b97698d53c48612f8c948153fb0b17/API.md#serialize) function that takes care of everything
