### ISSUE TITLE
https issue for inserting youtube embed

### ISSUE THREAD

**Issue by robin-epicswan** [orthes/medium-editor-insert-plugin#465]
Hi,

First, thank you for this awesome application !

I have a problème to insert youtube, facebook, vimeo or others embeded contents.

After pasting links, it doesn't work, and I hav that bad line in the console : 
`Mixed Content: The page at 'xxx' was loaded over HTTPS, but requested an insecure XMLHttpRequest endpoint 'http://medium.iframe.ly/api/oembed?iframe=1&url=https%3A%2F%2Fwww.youtube.com%2Fwatch%3Fv%3D7eW8BiNZkvE&_=1528706312159'. This request has been blocked; the content must be served over HTTPS.`

Https version of http://medium.iframe.ly/api/oembed?iframe=1&url=https%3A%2F%2Fwww.youtube.com%2Fwatch%3Fv%3D7eW8BiNZkvE&_=1528706312159 doesn't exist :-(

is there any way to resolve this issue, to use medium-editor on https websites ?

Thanks in advance !
Robin

**Comment by orthes** [comment]
https://github.com/orthes/medium-editor-insert-plugin/issues/448#issuecomment-365019719
