### ISSUE TITLE
uploadCompleted does not work

### ISSUE THREAD

**Issue by TrubinEN** [orthes/medium-editor-insert-plugin#467]
The following code does not work
`var editor = new MediumEditor(".editor");

$(function() {
  $(".editor").mediumInsert({
    editor: editor,
    addons: {
      images: {
        uploadCompleted: function($el, data) {
          console.log("test");
        }
      }
    }
  });
});`

Nothing displays after loading an image

**Comment by rbsl-yasmin** [comment]
It will trigger only if you're uploading your images on the server and return a response in the format they've given in the following link -
[https://github.com/orthes/medium-editor-insert-plugin/wiki/v2.x-Server-response](url)
