### ISSUE TITLE
_WEBPACK_IMPORTED_MODULE_ is not a constructor

### ISSUE THREAD

**Issue by AlexDemzz** [orthes/medium-editor-insert-plugin#470]
Hello, i tried to include this extension (v3.0) but like this 

`import * as MediumEditorInsert from "medium-editor-insert-plugin"`

```
const editor = new MediumEditor(".mediumEditor", {
            extensions: {
                'insert': new MediumEditorInsert()
            }});
```

but i get 
`TypeError: __WEBPACK_IMPORTED_MODULE_15_medium_editor_insert_plugin__ is not a constructor`

have you any idea about this bug ?

**Comment by orthes** [comment]
Try `import MediumEditorInsert from "medium-editor-insert-plugin"` insetad. v3.0 is not ready to be used in production yet
