### ISSUE TITLE
Right Click on Image Caption (Figcaption Tag), chrome is getting Crashed in MAC machine 

### ISSUE THREAD

**Issue by ajagadees** [orthes/medium-editor-insert-plugin#472]
![chrome crashed on mac](https://user-images.githubusercontent.com/4092697/44539944-17cffa00-a723-11e8-9da5-47495ad389cb.jpg)

**Comment by orthes** [comment]
Can't reproduce. Please provide repro steps and ideally jsfiddle/codepen with working example of the  issue
