### ISSUE TITLE
Upload image without base64?

### ISSUE THREAD

**Issue by mypetertw** [orthes/medium-editor-insert-plugin#476]
I wanna change upload image without base64. But how?
I looking for `medium-editor-insert-plugin.js` and found `fileUploadOptions` and change the url `null` to 'upload.php', also copy the upload.php and UploadHandler.php files on the same dir.
but still, always base64...

**Comment by orthes** [comment]
There's a `preview` option for images addon. Set it to false. https://github.com/orthes/medium-editor-insert-plugin/wiki/v2.x-Configuration#images-options
