### ISSUE TITLE
Add editable caption to figure

### ISSUE THREAD

**Issue by enzoz** [orthes/medium-editor-insert-plugin#54]
Any plans to add figcaption to figure? 

Maybe something like that this:
```html
<figure>
   <img src="..." draggable="true" alt="">
   <figcaption>Some Text Here</figcaption>
</figure>
```
With an icon, aside resize and remove icons, to change the caption value. Or just make it editable.

**Comment by bumblebeeman** [comment]
@orthes Does this work now? I would find it really useful!

Thanks
